=begin
#fastcomments

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.19.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for FastCommentsClient::APICommentBaseMeta
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe FastCommentsClient::APICommentBaseMeta do
  #let(:instance) { FastCommentsClient::APICommentBaseMeta.new }

  describe 'test an instance of APICommentBaseMeta' do
    it 'should create an instance of APICommentBaseMeta' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(FastCommentsClient::APICommentBaseMeta)
    end
  end

  describe 'test attribute "wp_user_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "wp_post_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
