=begin
#fastcomments

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.18.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for FastCommentsClient::FindCommentsByRangeResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe FastCommentsClient::FindCommentsByRangeResponse do
  #let(:instance) { FastCommentsClient::FindCommentsByRangeResponse.new }

  describe 'test an instance of FindCommentsByRangeResponse' do
    it 'should create an instance of FindCommentsByRangeResponse' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(FastCommentsClient::FindCommentsByRangeResponse)
    end
  end

  describe 'test attribute "results"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "created_at"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
