=begin
#fastcomments

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for FastCommentsClient::ImageContentProfanityLevel
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe FastCommentsClient::ImageContentProfanityLevel do
  let(:instance) { FastCommentsClient::ImageContentProfanityLevel.new }

  describe 'test an instance of ImageContentProfanityLevel' do
    it 'should create an instance of ImageContentProfanityLevel' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(FastCommentsClient::ImageContentProfanityLevel)
    end
  end

end
