=begin
#fastcomments

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.19.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for FastCommentsClient::QuestionConfigCustomOptionsInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe FastCommentsClient::QuestionConfigCustomOptionsInner do
  #let(:instance) { FastCommentsClient::QuestionConfigCustomOptionsInner.new }

  describe 'test an instance of QuestionConfigCustomOptionsInner' do
    it 'should create an instance of QuestionConfigCustomOptionsInner' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(FastCommentsClient::QuestionConfigCustomOptionsInner)
    end
  end

  describe 'test attribute "image_src"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
