=begin
#fastcomments

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.19.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for FastCommentsClient::SizePreset
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe FastCommentsClient::SizePreset do
  #let(:instance) { FastCommentsClient::SizePreset.new }

  describe 'test an instance of SizePreset' do
    it 'should create an instance of SizePreset' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(FastCommentsClient::SizePreset)
    end
  end

end
