=begin
#fastcomments

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.19.0-SNAPSHOT

=end

require 'date'
require 'time'

module FastCommentsClient
  class APIStatus
    SUCCESS = "success".freeze
    FAILED = "failed".freeze

    def self.all_vars
      @all_vars ||= [SUCCESS, FAILED].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if APIStatus.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #APIStatus"
    end
  end
end
