=begin
#fastcomments

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'date'
require 'time'

module FastCommentsClient
  class APIComment
    attr_accessor :_id

    attr_accessor :ai_determined_spam

    attr_accessor :anon_user_id

    attr_accessor :approved

    attr_accessor :avatar_src

    attr_accessor :badges

    attr_accessor :comment

    attr_accessor :comment_html

    attr_accessor :commenter_email

    attr_accessor :commenter_link

    attr_accessor :commenter_name

    attr_accessor :date

    attr_accessor :display_label

    attr_accessor :domain

    attr_accessor :external_id

    attr_accessor :external_parent_id

    attr_accessor :expire_at

    attr_accessor :feedback_ids

    attr_accessor :flag_count

    attr_accessor :from_product_id

    attr_accessor :has_code

    attr_accessor :has_images

    attr_accessor :has_links

    attr_accessor :hash_tags

    attr_accessor :is_by_admin

    attr_accessor :is_by_moderator

    attr_accessor :is_deleted

    attr_accessor :is_deleted_user

    attr_accessor :is_pinned

    attr_accessor :is_locked

    attr_accessor :is_spam

    attr_accessor :local_date_hours

    attr_accessor :local_date_string

    attr_accessor :locale

    attr_accessor :mentions

    attr_accessor :meta

    attr_accessor :moderation_group_ids

    attr_accessor :notification_sent_for_parent

    attr_accessor :notification_sent_for_parent_tenant

    attr_accessor :page_title

    attr_accessor :parent_id

    attr_accessor :rating

    attr_accessor :reviewed

    attr_accessor :tenant_id

    attr_accessor :url

    attr_accessor :url_id

    attr_accessor :url_id_raw

    attr_accessor :user_id

    attr_accessor :verified

    attr_accessor :verified_date

    attr_accessor :votes

    attr_accessor :votes_down

    attr_accessor :votes_up

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'_id' => :'_id',
        :'ai_determined_spam' => :'aiDeterminedSpam',
        :'anon_user_id' => :'anonUserId',
        :'approved' => :'approved',
        :'avatar_src' => :'avatarSrc',
        :'badges' => :'badges',
        :'comment' => :'comment',
        :'comment_html' => :'commentHTML',
        :'commenter_email' => :'commenterEmail',
        :'commenter_link' => :'commenterLink',
        :'commenter_name' => :'commenterName',
        :'date' => :'date',
        :'display_label' => :'displayLabel',
        :'domain' => :'domain',
        :'external_id' => :'externalId',
        :'external_parent_id' => :'externalParentId',
        :'expire_at' => :'expireAt',
        :'feedback_ids' => :'feedbackIds',
        :'flag_count' => :'flagCount',
        :'from_product_id' => :'fromProductId',
        :'has_code' => :'hasCode',
        :'has_images' => :'hasImages',
        :'has_links' => :'hasLinks',
        :'hash_tags' => :'hashTags',
        :'is_by_admin' => :'isByAdmin',
        :'is_by_moderator' => :'isByModerator',
        :'is_deleted' => :'isDeleted',
        :'is_deleted_user' => :'isDeletedUser',
        :'is_pinned' => :'isPinned',
        :'is_locked' => :'isLocked',
        :'is_spam' => :'isSpam',
        :'local_date_hours' => :'localDateHours',
        :'local_date_string' => :'localDateString',
        :'locale' => :'locale',
        :'mentions' => :'mentions',
        :'meta' => :'meta',
        :'moderation_group_ids' => :'moderationGroupIds',
        :'notification_sent_for_parent' => :'notificationSentForParent',
        :'notification_sent_for_parent_tenant' => :'notificationSentForParentTenant',
        :'page_title' => :'pageTitle',
        :'parent_id' => :'parentId',
        :'rating' => :'rating',
        :'reviewed' => :'reviewed',
        :'tenant_id' => :'tenantId',
        :'url' => :'url',
        :'url_id' => :'urlId',
        :'url_id_raw' => :'urlIdRaw',
        :'user_id' => :'userId',
        :'verified' => :'verified',
        :'verified_date' => :'verifiedDate',
        :'votes' => :'votes',
        :'votes_down' => :'votesDown',
        :'votes_up' => :'votesUp'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'_id' => :'String',
        :'ai_determined_spam' => :'Boolean',
        :'anon_user_id' => :'String',
        :'approved' => :'Boolean',
        :'avatar_src' => :'String',
        :'badges' => :'Array<CommentUserBadgeInfo>',
        :'comment' => :'String',
        :'comment_html' => :'String',
        :'commenter_email' => :'String',
        :'commenter_link' => :'String',
        :'commenter_name' => :'String',
        :'date' => :'Float',
        :'display_label' => :'String',
        :'domain' => :'String',
        :'external_id' => :'String',
        :'external_parent_id' => :'String',
        :'expire_at' => :'Time',
        :'feedback_ids' => :'Array<String>',
        :'flag_count' => :'Integer',
        :'from_product_id' => :'Integer',
        :'has_code' => :'Boolean',
        :'has_images' => :'Boolean',
        :'has_links' => :'Boolean',
        :'hash_tags' => :'Array<CommentUserHashTagInfo>',
        :'is_by_admin' => :'Boolean',
        :'is_by_moderator' => :'Boolean',
        :'is_deleted' => :'Boolean',
        :'is_deleted_user' => :'Boolean',
        :'is_pinned' => :'Boolean',
        :'is_locked' => :'Boolean',
        :'is_spam' => :'Boolean',
        :'local_date_hours' => :'Integer',
        :'local_date_string' => :'String',
        :'locale' => :'String',
        :'mentions' => :'Array<CommentUserMentionInfo>',
        :'meta' => :'FCommentMeta',
        :'moderation_group_ids' => :'Array<String>',
        :'notification_sent_for_parent' => :'Boolean',
        :'notification_sent_for_parent_tenant' => :'Boolean',
        :'page_title' => :'String',
        :'parent_id' => :'String',
        :'rating' => :'Float',
        :'reviewed' => :'Boolean',
        :'tenant_id' => :'String',
        :'url' => :'String',
        :'url_id' => :'String',
        :'url_id_raw' => :'String',
        :'user_id' => :'String',
        :'verified' => :'Boolean',
        :'verified_date' => :'Time',
        :'votes' => :'Integer',
        :'votes_down' => :'Integer',
        :'votes_up' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'anon_user_id',
        :'avatar_src',
        :'badges',
        :'commenter_email',
        :'commenter_link',
        :'date',
        :'display_label',
        :'domain',
        :'external_parent_id',
        :'expire_at',
        :'flag_count',
        :'is_pinned',
        :'is_locked',
        :'local_date_hours',
        :'local_date_string',
        :'locale',
        :'meta',
        :'moderation_group_ids',
        :'page_title',
        :'parent_id',
        :'rating',
        :'user_id',
        :'verified_date',
        :'votes',
        :'votes_down',
        :'votes_up'
      ])
    end

    # List of class defined in allOf (OpenAPI v3)
    def self.openapi_all_of
      [
      :'APICommentBase'
      ]
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `FastCommentsClient::APIComment` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `FastCommentsClient::APIComment`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'_id')
        self._id = attributes[:'_id']
      else
        self._id = nil
      end

      if attributes.key?(:'ai_determined_spam')
        self.ai_determined_spam = attributes[:'ai_determined_spam']
      end

      if attributes.key?(:'anon_user_id')
        self.anon_user_id = attributes[:'anon_user_id']
      end

      if attributes.key?(:'approved')
        self.approved = attributes[:'approved']
      else
        self.approved = nil
      end

      if attributes.key?(:'avatar_src')
        self.avatar_src = attributes[:'avatar_src']
      end

      if attributes.key?(:'badges')
        if (value = attributes[:'badges']).is_a?(Array)
          self.badges = value
        end
      end

      if attributes.key?(:'comment')
        self.comment = attributes[:'comment']
      else
        self.comment = nil
      end

      if attributes.key?(:'comment_html')
        self.comment_html = attributes[:'comment_html']
      else
        self.comment_html = nil
      end

      if attributes.key?(:'commenter_email')
        self.commenter_email = attributes[:'commenter_email']
      end

      if attributes.key?(:'commenter_link')
        self.commenter_link = attributes[:'commenter_link']
      end

      if attributes.key?(:'commenter_name')
        self.commenter_name = attributes[:'commenter_name']
      else
        self.commenter_name = nil
      end

      if attributes.key?(:'date')
        self.date = attributes[:'date']
      else
        self.date = nil
      end

      if attributes.key?(:'display_label')
        self.display_label = attributes[:'display_label']
      end

      if attributes.key?(:'domain')
        self.domain = attributes[:'domain']
      end

      if attributes.key?(:'external_id')
        self.external_id = attributes[:'external_id']
      end

      if attributes.key?(:'external_parent_id')
        self.external_parent_id = attributes[:'external_parent_id']
      end

      if attributes.key?(:'expire_at')
        self.expire_at = attributes[:'expire_at']
      end

      if attributes.key?(:'feedback_ids')
        if (value = attributes[:'feedback_ids']).is_a?(Array)
          self.feedback_ids = value
        end
      end

      if attributes.key?(:'flag_count')
        self.flag_count = attributes[:'flag_count']
      end

      if attributes.key?(:'from_product_id')
        self.from_product_id = attributes[:'from_product_id']
      end

      if attributes.key?(:'has_code')
        self.has_code = attributes[:'has_code']
      end

      if attributes.key?(:'has_images')
        self.has_images = attributes[:'has_images']
      end

      if attributes.key?(:'has_links')
        self.has_links = attributes[:'has_links']
      end

      if attributes.key?(:'hash_tags')
        if (value = attributes[:'hash_tags']).is_a?(Array)
          self.hash_tags = value
        end
      end

      if attributes.key?(:'is_by_admin')
        self.is_by_admin = attributes[:'is_by_admin']
      end

      if attributes.key?(:'is_by_moderator')
        self.is_by_moderator = attributes[:'is_by_moderator']
      end

      if attributes.key?(:'is_deleted')
        self.is_deleted = attributes[:'is_deleted']
      end

      if attributes.key?(:'is_deleted_user')
        self.is_deleted_user = attributes[:'is_deleted_user']
      end

      if attributes.key?(:'is_pinned')
        self.is_pinned = attributes[:'is_pinned']
      end

      if attributes.key?(:'is_locked')
        self.is_locked = attributes[:'is_locked']
      end

      if attributes.key?(:'is_spam')
        self.is_spam = attributes[:'is_spam']
      end

      if attributes.key?(:'local_date_hours')
        self.local_date_hours = attributes[:'local_date_hours']
      end

      if attributes.key?(:'local_date_string')
        self.local_date_string = attributes[:'local_date_string']
      end

      if attributes.key?(:'locale')
        self.locale = attributes[:'locale']
      else
        self.locale = nil
      end

      if attributes.key?(:'mentions')
        if (value = attributes[:'mentions']).is_a?(Array)
          self.mentions = value
        end
      end

      if attributes.key?(:'meta')
        self.meta = attributes[:'meta']
      end

      if attributes.key?(:'moderation_group_ids')
        if (value = attributes[:'moderation_group_ids']).is_a?(Array)
          self.moderation_group_ids = value
        end
      end

      if attributes.key?(:'notification_sent_for_parent')
        self.notification_sent_for_parent = attributes[:'notification_sent_for_parent']
      end

      if attributes.key?(:'notification_sent_for_parent_tenant')
        self.notification_sent_for_parent_tenant = attributes[:'notification_sent_for_parent_tenant']
      end

      if attributes.key?(:'page_title')
        self.page_title = attributes[:'page_title']
      end

      if attributes.key?(:'parent_id')
        self.parent_id = attributes[:'parent_id']
      end

      if attributes.key?(:'rating')
        self.rating = attributes[:'rating']
      end

      if attributes.key?(:'reviewed')
        self.reviewed = attributes[:'reviewed']
      end

      if attributes.key?(:'tenant_id')
        self.tenant_id = attributes[:'tenant_id']
      else
        self.tenant_id = nil
      end

      if attributes.key?(:'url')
        self.url = attributes[:'url']
      else
        self.url = nil
      end

      if attributes.key?(:'url_id')
        self.url_id = attributes[:'url_id']
      else
        self.url_id = nil
      end

      if attributes.key?(:'url_id_raw')
        self.url_id_raw = attributes[:'url_id_raw']
      end

      if attributes.key?(:'user_id')
        self.user_id = attributes[:'user_id']
      end

      if attributes.key?(:'verified')
        self.verified = attributes[:'verified']
      else
        self.verified = nil
      end

      if attributes.key?(:'verified_date')
        self.verified_date = attributes[:'verified_date']
      end

      if attributes.key?(:'votes')
        self.votes = attributes[:'votes']
      end

      if attributes.key?(:'votes_down')
        self.votes_down = attributes[:'votes_down']
      end

      if attributes.key?(:'votes_up')
        self.votes_up = attributes[:'votes_up']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @_id.nil?
        invalid_properties.push('invalid value for "_id", _id cannot be nil.')
      end

      if @approved.nil?
        invalid_properties.push('invalid value for "approved", approved cannot be nil.')
      end

      if @comment.nil?
        invalid_properties.push('invalid value for "comment", comment cannot be nil.')
      end

      if @comment_html.nil?
        invalid_properties.push('invalid value for "comment_html", comment_html cannot be nil.')
      end

      if @commenter_name.nil?
        invalid_properties.push('invalid value for "commenter_name", commenter_name cannot be nil.')
      end

      if @tenant_id.nil?
        invalid_properties.push('invalid value for "tenant_id", tenant_id cannot be nil.')
      end

      if @url.nil?
        invalid_properties.push('invalid value for "url", url cannot be nil.')
      end

      if @url_id.nil?
        invalid_properties.push('invalid value for "url_id", url_id cannot be nil.')
      end

      if @verified.nil?
        invalid_properties.push('invalid value for "verified", verified cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @_id.nil?
      return false if @approved.nil?
      return false if @comment.nil?
      return false if @comment_html.nil?
      return false if @commenter_name.nil?
      return false if @tenant_id.nil?
      return false if @url.nil?
      return false if @url_id.nil?
      return false if @verified.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] _id Value to be assigned
    def _id=(_id)
      if _id.nil?
        fail ArgumentError, '_id cannot be nil'
      end

      @_id = _id
    end

    # Custom attribute writer method with validation
    # @param [Object] approved Value to be assigned
    def approved=(approved)
      if approved.nil?
        fail ArgumentError, 'approved cannot be nil'
      end

      @approved = approved
    end

    # Custom attribute writer method with validation
    # @param [Object] comment Value to be assigned
    def comment=(comment)
      if comment.nil?
        fail ArgumentError, 'comment cannot be nil'
      end

      @comment = comment
    end

    # Custom attribute writer method with validation
    # @param [Object] comment_html Value to be assigned
    def comment_html=(comment_html)
      if comment_html.nil?
        fail ArgumentError, 'comment_html cannot be nil'
      end

      @comment_html = comment_html
    end

    # Custom attribute writer method with validation
    # @param [Object] commenter_name Value to be assigned
    def commenter_name=(commenter_name)
      if commenter_name.nil?
        fail ArgumentError, 'commenter_name cannot be nil'
      end

      @commenter_name = commenter_name
    end

    # Custom attribute writer method with validation
    # @param [Object] tenant_id Value to be assigned
    def tenant_id=(tenant_id)
      if tenant_id.nil?
        fail ArgumentError, 'tenant_id cannot be nil'
      end

      @tenant_id = tenant_id
    end

    # Custom attribute writer method with validation
    # @param [Object] url Value to be assigned
    def url=(url)
      if url.nil?
        fail ArgumentError, 'url cannot be nil'
      end

      @url = url
    end

    # Custom attribute writer method with validation
    # @param [Object] url_id Value to be assigned
    def url_id=(url_id)
      if url_id.nil?
        fail ArgumentError, 'url_id cannot be nil'
      end

      @url_id = url_id
    end

    # Custom attribute writer method with validation
    # @param [Object] verified Value to be assigned
    def verified=(verified)
      if verified.nil?
        fail ArgumentError, 'verified cannot be nil'
      end

      @verified = verified
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          _id == o._id &&
          ai_determined_spam == o.ai_determined_spam &&
          anon_user_id == o.anon_user_id &&
          approved == o.approved &&
          avatar_src == o.avatar_src &&
          badges == o.badges &&
          comment == o.comment &&
          comment_html == o.comment_html &&
          commenter_email == o.commenter_email &&
          commenter_link == o.commenter_link &&
          commenter_name == o.commenter_name &&
          date == o.date &&
          display_label == o.display_label &&
          domain == o.domain &&
          external_id == o.external_id &&
          external_parent_id == o.external_parent_id &&
          expire_at == o.expire_at &&
          feedback_ids == o.feedback_ids &&
          flag_count == o.flag_count &&
          from_product_id == o.from_product_id &&
          has_code == o.has_code &&
          has_images == o.has_images &&
          has_links == o.has_links &&
          hash_tags == o.hash_tags &&
          is_by_admin == o.is_by_admin &&
          is_by_moderator == o.is_by_moderator &&
          is_deleted == o.is_deleted &&
          is_deleted_user == o.is_deleted_user &&
          is_pinned == o.is_pinned &&
          is_locked == o.is_locked &&
          is_spam == o.is_spam &&
          local_date_hours == o.local_date_hours &&
          local_date_string == o.local_date_string &&
          locale == o.locale &&
          mentions == o.mentions &&
          meta == o.meta &&
          moderation_group_ids == o.moderation_group_ids &&
          notification_sent_for_parent == o.notification_sent_for_parent &&
          notification_sent_for_parent_tenant == o.notification_sent_for_parent_tenant &&
          page_title == o.page_title &&
          parent_id == o.parent_id &&
          rating == o.rating &&
          reviewed == o.reviewed &&
          tenant_id == o.tenant_id &&
          url == o.url &&
          url_id == o.url_id &&
          url_id_raw == o.url_id_raw &&
          user_id == o.user_id &&
          verified == o.verified &&
          verified_date == o.verified_date &&
          votes == o.votes &&
          votes_down == o.votes_down &&
          votes_up == o.votes_up
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [_id, ai_determined_spam, anon_user_id, approved, avatar_src, badges, comment, comment_html, commenter_email, commenter_link, commenter_name, date, display_label, domain, external_id, external_parent_id, expire_at, feedback_ids, flag_count, from_product_id, has_code, has_images, has_links, hash_tags, is_by_admin, is_by_moderator, is_deleted, is_deleted_user, is_pinned, is_locked, is_spam, local_date_hours, local_date_string, locale, mentions, meta, moderation_group_ids, notification_sent_for_parent, notification_sent_for_parent_tenant, page_title, parent_id, rating, reviewed, tenant_id, url, url_id, url_id_raw, user_id, verified, verified_date, votes, votes_down, votes_up].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = FastCommentsClient.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
