=begin
#fastcomments

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.18.0-SNAPSHOT

=end

require 'date'
require 'time'

module FastCommentsClient
  class APIDomainConfiguration < ApiModelBase
    attr_accessor :id

    attr_accessor :domain

    attr_accessor :email_from_name

    attr_accessor :email_from_email

    # Construct a type with a set of properties K of type T
    attr_accessor :email_headers

    attr_accessor :wp_sync_token

    attr_accessor :wp_synced

    attr_accessor :wp_url

    attr_accessor :created_at

    attr_accessor :auto_added_date

    attr_accessor :site_type

    attr_accessor :logo_src

    attr_accessor :logo_src100px

    attr_accessor :footer_unsubscribe_url

    attr_accessor :disable_unsubscribe_links

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'domain' => :'domain',
        :'email_from_name' => :'emailFromName',
        :'email_from_email' => :'emailFromEmail',
        :'email_headers' => :'emailHeaders',
        :'wp_sync_token' => :'wpSyncToken',
        :'wp_synced' => :'wpSynced',
        :'wp_url' => :'wpURL',
        :'created_at' => :'createdAt',
        :'auto_added_date' => :'autoAddedDate',
        :'site_type' => :'siteType',
        :'logo_src' => :'logoSrc',
        :'logo_src100px' => :'logoSrc100px',
        :'footer_unsubscribe_url' => :'footerUnsubscribeURL',
        :'disable_unsubscribe_links' => :'disableUnsubscribeLinks'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'domain' => :'String',
        :'email_from_name' => :'String',
        :'email_from_email' => :'String',
        :'email_headers' => :'Hash<String, String>',
        :'wp_sync_token' => :'String',
        :'wp_synced' => :'Boolean',
        :'wp_url' => :'String',
        :'created_at' => :'Time',
        :'auto_added_date' => :'Time',
        :'site_type' => :'ImportedSiteType',
        :'logo_src' => :'String',
        :'logo_src100px' => :'String',
        :'footer_unsubscribe_url' => :'String',
        :'disable_unsubscribe_links' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'email_from_name',
        :'email_from_email',
        :'wp_sync_token',
        :'wp_url',
        :'logo_src',
        :'logo_src100px',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `FastCommentsClient::APIDomainConfiguration` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `FastCommentsClient::APIDomainConfiguration`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'domain')
        self.domain = attributes[:'domain']
      else
        self.domain = nil
      end

      if attributes.key?(:'email_from_name')
        self.email_from_name = attributes[:'email_from_name']
      end

      if attributes.key?(:'email_from_email')
        self.email_from_email = attributes[:'email_from_email']
      end

      if attributes.key?(:'email_headers')
        if (value = attributes[:'email_headers']).is_a?(Hash)
          self.email_headers = value
        end
      end

      if attributes.key?(:'wp_sync_token')
        self.wp_sync_token = attributes[:'wp_sync_token']
      end

      if attributes.key?(:'wp_synced')
        self.wp_synced = attributes[:'wp_synced']
      end

      if attributes.key?(:'wp_url')
        self.wp_url = attributes[:'wp_url']
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      else
        self.created_at = nil
      end

      if attributes.key?(:'auto_added_date')
        self.auto_added_date = attributes[:'auto_added_date']
      end

      if attributes.key?(:'site_type')
        self.site_type = attributes[:'site_type']
      end

      if attributes.key?(:'logo_src')
        self.logo_src = attributes[:'logo_src']
      end

      if attributes.key?(:'logo_src100px')
        self.logo_src100px = attributes[:'logo_src100px']
      end

      if attributes.key?(:'footer_unsubscribe_url')
        self.footer_unsubscribe_url = attributes[:'footer_unsubscribe_url']
      end

      if attributes.key?(:'disable_unsubscribe_links')
        self.disable_unsubscribe_links = attributes[:'disable_unsubscribe_links']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @domain.nil?
        invalid_properties.push('invalid value for "domain", domain cannot be nil.')
      end

      if @created_at.nil?
        invalid_properties.push('invalid value for "created_at", created_at cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @domain.nil?
      return false if @created_at.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] domain Value to be assigned
    def domain=(domain)
      if domain.nil?
        fail ArgumentError, 'domain cannot be nil'
      end

      @domain = domain
    end

    # Custom attribute writer method with validation
    # @param [Object] created_at Value to be assigned
    def created_at=(created_at)
      if created_at.nil?
        fail ArgumentError, 'created_at cannot be nil'
      end

      @created_at = created_at
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          domain == o.domain &&
          email_from_name == o.email_from_name &&
          email_from_email == o.email_from_email &&
          email_headers == o.email_headers &&
          wp_sync_token == o.wp_sync_token &&
          wp_synced == o.wp_synced &&
          wp_url == o.wp_url &&
          created_at == o.created_at &&
          auto_added_date == o.auto_added_date &&
          site_type == o.site_type &&
          logo_src == o.logo_src &&
          logo_src100px == o.logo_src100px &&
          footer_unsubscribe_url == o.footer_unsubscribe_url &&
          disable_unsubscribe_links == o.disable_unsubscribe_links
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, domain, email_from_name, email_from_email, email_headers, wp_sync_token, wp_synced, wp_url, created_at, auto_added_date, site_type, logo_src, logo_src100px, footer_unsubscribe_url, disable_unsubscribe_links].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
