=begin
#fastcomments

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.18.0-SNAPSHOT

=end

require 'date'
require 'time'

module FastCommentsClient
  class APISSOUser < ApiModelBase
    attr_accessor :id

    attr_accessor :username

    attr_accessor :website_url

    attr_accessor :email

    attr_accessor :sign_up_date

    attr_accessor :created_from_url_id

    attr_accessor :login_count

    attr_accessor :avatar_src

    attr_accessor :opted_in_notifications

    attr_accessor :opted_in_subscription_notifications

    attr_accessor :display_label

    attr_accessor :display_name

    attr_accessor :is_account_owner

    attr_accessor :is_admin_admin

    attr_accessor :is_comment_moderator_admin

    attr_accessor :is_profile_activity_private

    attr_accessor :is_profile_comments_private

    attr_accessor :is_profile_dm_disabled

    attr_accessor :has_blocked_users

    attr_accessor :group_ids

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'username' => :'username',
        :'website_url' => :'websiteUrl',
        :'email' => :'email',
        :'sign_up_date' => :'signUpDate',
        :'created_from_url_id' => :'createdFromUrlId',
        :'login_count' => :'loginCount',
        :'avatar_src' => :'avatarSrc',
        :'opted_in_notifications' => :'optedInNotifications',
        :'opted_in_subscription_notifications' => :'optedInSubscriptionNotifications',
        :'display_label' => :'displayLabel',
        :'display_name' => :'displayName',
        :'is_account_owner' => :'isAccountOwner',
        :'is_admin_admin' => :'isAdminAdmin',
        :'is_comment_moderator_admin' => :'isCommentModeratorAdmin',
        :'is_profile_activity_private' => :'isProfileActivityPrivate',
        :'is_profile_comments_private' => :'isProfileCommentsPrivate',
        :'is_profile_dm_disabled' => :'isProfileDMDisabled',
        :'has_blocked_users' => :'hasBlockedUsers',
        :'group_ids' => :'groupIds'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'username' => :'String',
        :'website_url' => :'String',
        :'email' => :'String',
        :'sign_up_date' => :'Integer',
        :'created_from_url_id' => :'String',
        :'login_count' => :'Integer',
        :'avatar_src' => :'String',
        :'opted_in_notifications' => :'Boolean',
        :'opted_in_subscription_notifications' => :'Boolean',
        :'display_label' => :'String',
        :'display_name' => :'String',
        :'is_account_owner' => :'Boolean',
        :'is_admin_admin' => :'Boolean',
        :'is_comment_moderator_admin' => :'Boolean',
        :'is_profile_activity_private' => :'Boolean',
        :'is_profile_comments_private' => :'Boolean',
        :'is_profile_dm_disabled' => :'Boolean',
        :'has_blocked_users' => :'Boolean',
        :'group_ids' => :'Array<String>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `FastCommentsClient::APISSOUser` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `FastCommentsClient::APISSOUser`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'username')
        self.username = attributes[:'username']
      else
        self.username = nil
      end

      if attributes.key?(:'website_url')
        self.website_url = attributes[:'website_url']
      else
        self.website_url = nil
      end

      if attributes.key?(:'email')
        self.email = attributes[:'email']
      else
        self.email = nil
      end

      if attributes.key?(:'sign_up_date')
        self.sign_up_date = attributes[:'sign_up_date']
      else
        self.sign_up_date = nil
      end

      if attributes.key?(:'created_from_url_id')
        self.created_from_url_id = attributes[:'created_from_url_id']
      else
        self.created_from_url_id = nil
      end

      if attributes.key?(:'login_count')
        self.login_count = attributes[:'login_count']
      else
        self.login_count = nil
      end

      if attributes.key?(:'avatar_src')
        self.avatar_src = attributes[:'avatar_src']
      else
        self.avatar_src = nil
      end

      if attributes.key?(:'opted_in_notifications')
        self.opted_in_notifications = attributes[:'opted_in_notifications']
      else
        self.opted_in_notifications = nil
      end

      if attributes.key?(:'opted_in_subscription_notifications')
        self.opted_in_subscription_notifications = attributes[:'opted_in_subscription_notifications']
      else
        self.opted_in_subscription_notifications = nil
      end

      if attributes.key?(:'display_label')
        self.display_label = attributes[:'display_label']
      else
        self.display_label = nil
      end

      if attributes.key?(:'display_name')
        self.display_name = attributes[:'display_name']
      else
        self.display_name = nil
      end

      if attributes.key?(:'is_account_owner')
        self.is_account_owner = attributes[:'is_account_owner']
      end

      if attributes.key?(:'is_admin_admin')
        self.is_admin_admin = attributes[:'is_admin_admin']
      end

      if attributes.key?(:'is_comment_moderator_admin')
        self.is_comment_moderator_admin = attributes[:'is_comment_moderator_admin']
      end

      if attributes.key?(:'is_profile_activity_private')
        self.is_profile_activity_private = attributes[:'is_profile_activity_private']
      end

      if attributes.key?(:'is_profile_comments_private')
        self.is_profile_comments_private = attributes[:'is_profile_comments_private']
      end

      if attributes.key?(:'is_profile_dm_disabled')
        self.is_profile_dm_disabled = attributes[:'is_profile_dm_disabled']
      end

      if attributes.key?(:'has_blocked_users')
        self.has_blocked_users = attributes[:'has_blocked_users']
      end

      if attributes.key?(:'group_ids')
        if (value = attributes[:'group_ids']).is_a?(Array)
          self.group_ids = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @username.nil?
        invalid_properties.push('invalid value for "username", username cannot be nil.')
      end

      if @website_url.nil?
        invalid_properties.push('invalid value for "website_url", website_url cannot be nil.')
      end

      if @email.nil?
        invalid_properties.push('invalid value for "email", email cannot be nil.')
      end

      if @sign_up_date.nil?
        invalid_properties.push('invalid value for "sign_up_date", sign_up_date cannot be nil.')
      end

      if @created_from_url_id.nil?
        invalid_properties.push('invalid value for "created_from_url_id", created_from_url_id cannot be nil.')
      end

      if @login_count.nil?
        invalid_properties.push('invalid value for "login_count", login_count cannot be nil.')
      end

      if @avatar_src.nil?
        invalid_properties.push('invalid value for "avatar_src", avatar_src cannot be nil.')
      end

      if @opted_in_notifications.nil?
        invalid_properties.push('invalid value for "opted_in_notifications", opted_in_notifications cannot be nil.')
      end

      if @opted_in_subscription_notifications.nil?
        invalid_properties.push('invalid value for "opted_in_subscription_notifications", opted_in_subscription_notifications cannot be nil.')
      end

      if @display_label.nil?
        invalid_properties.push('invalid value for "display_label", display_label cannot be nil.')
      end

      if @display_name.nil?
        invalid_properties.push('invalid value for "display_name", display_name cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @username.nil?
      return false if @website_url.nil?
      return false if @email.nil?
      return false if @sign_up_date.nil?
      return false if @created_from_url_id.nil?
      return false if @login_count.nil?
      return false if @avatar_src.nil?
      return false if @opted_in_notifications.nil?
      return false if @opted_in_subscription_notifications.nil?
      return false if @display_label.nil?
      return false if @display_name.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] username Value to be assigned
    def username=(username)
      if username.nil?
        fail ArgumentError, 'username cannot be nil'
      end

      @username = username
    end

    # Custom attribute writer method with validation
    # @param [Object] website_url Value to be assigned
    def website_url=(website_url)
      if website_url.nil?
        fail ArgumentError, 'website_url cannot be nil'
      end

      @website_url = website_url
    end

    # Custom attribute writer method with validation
    # @param [Object] email Value to be assigned
    def email=(email)
      if email.nil?
        fail ArgumentError, 'email cannot be nil'
      end

      @email = email
    end

    # Custom attribute writer method with validation
    # @param [Object] sign_up_date Value to be assigned
    def sign_up_date=(sign_up_date)
      if sign_up_date.nil?
        fail ArgumentError, 'sign_up_date cannot be nil'
      end

      @sign_up_date = sign_up_date
    end

    # Custom attribute writer method with validation
    # @param [Object] created_from_url_id Value to be assigned
    def created_from_url_id=(created_from_url_id)
      if created_from_url_id.nil?
        fail ArgumentError, 'created_from_url_id cannot be nil'
      end

      @created_from_url_id = created_from_url_id
    end

    # Custom attribute writer method with validation
    # @param [Object] login_count Value to be assigned
    def login_count=(login_count)
      if login_count.nil?
        fail ArgumentError, 'login_count cannot be nil'
      end

      @login_count = login_count
    end

    # Custom attribute writer method with validation
    # @param [Object] avatar_src Value to be assigned
    def avatar_src=(avatar_src)
      if avatar_src.nil?
        fail ArgumentError, 'avatar_src cannot be nil'
      end

      @avatar_src = avatar_src
    end

    # Custom attribute writer method with validation
    # @param [Object] opted_in_notifications Value to be assigned
    def opted_in_notifications=(opted_in_notifications)
      if opted_in_notifications.nil?
        fail ArgumentError, 'opted_in_notifications cannot be nil'
      end

      @opted_in_notifications = opted_in_notifications
    end

    # Custom attribute writer method with validation
    # @param [Object] opted_in_subscription_notifications Value to be assigned
    def opted_in_subscription_notifications=(opted_in_subscription_notifications)
      if opted_in_subscription_notifications.nil?
        fail ArgumentError, 'opted_in_subscription_notifications cannot be nil'
      end

      @opted_in_subscription_notifications = opted_in_subscription_notifications
    end

    # Custom attribute writer method with validation
    # @param [Object] display_label Value to be assigned
    def display_label=(display_label)
      if display_label.nil?
        fail ArgumentError, 'display_label cannot be nil'
      end

      @display_label = display_label
    end

    # Custom attribute writer method with validation
    # @param [Object] display_name Value to be assigned
    def display_name=(display_name)
      if display_name.nil?
        fail ArgumentError, 'display_name cannot be nil'
      end

      @display_name = display_name
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          username == o.username &&
          website_url == o.website_url &&
          email == o.email &&
          sign_up_date == o.sign_up_date &&
          created_from_url_id == o.created_from_url_id &&
          login_count == o.login_count &&
          avatar_src == o.avatar_src &&
          opted_in_notifications == o.opted_in_notifications &&
          opted_in_subscription_notifications == o.opted_in_subscription_notifications &&
          display_label == o.display_label &&
          display_name == o.display_name &&
          is_account_owner == o.is_account_owner &&
          is_admin_admin == o.is_admin_admin &&
          is_comment_moderator_admin == o.is_comment_moderator_admin &&
          is_profile_activity_private == o.is_profile_activity_private &&
          is_profile_comments_private == o.is_profile_comments_private &&
          is_profile_dm_disabled == o.is_profile_dm_disabled &&
          has_blocked_users == o.has_blocked_users &&
          group_ids == o.group_ids
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, username, website_url, email, sign_up_date, created_from_url_id, login_count, avatar_src, opted_in_notifications, opted_in_subscription_notifications, display_label, display_name, is_account_owner, is_admin_admin, is_comment_moderator_admin, is_profile_activity_private, is_profile_comments_private, is_profile_dm_disabled, has_blocked_users, group_ids].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
