=begin
#fastcomments

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.19.0-SNAPSHOT

=end

require 'date'
require 'time'

module FastCommentsClient
  class EmailTemplateDefinition < ApiModelBase
    attr_accessor :email_template_id

    # Construct a type with a set of properties K of type T
    attr_accessor :default_test_data

    # Construct a type with a set of properties K of type T
    attr_accessor :default_translations_by_locale

    attr_accessor :default_ejs

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'email_template_id' => :'emailTemplateId',
        :'default_test_data' => :'defaultTestData',
        :'default_translations_by_locale' => :'defaultTranslationsByLocale',
        :'default_ejs' => :'defaultEJS'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'email_template_id' => :'String',
        :'default_test_data' => :'Hash<String, Object>',
        :'default_translations_by_locale' => :'Hash<String, Hash>',
        :'default_ejs' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `FastCommentsClient::EmailTemplateDefinition` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `FastCommentsClient::EmailTemplateDefinition`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'email_template_id')
        self.email_template_id = attributes[:'email_template_id']
      else
        self.email_template_id = nil
      end

      if attributes.key?(:'default_test_data')
        if (value = attributes[:'default_test_data']).is_a?(Hash)
          self.default_test_data = value
        end
      else
        self.default_test_data = nil
      end

      if attributes.key?(:'default_translations_by_locale')
        if (value = attributes[:'default_translations_by_locale']).is_a?(Hash)
          self.default_translations_by_locale = value
        end
      else
        self.default_translations_by_locale = nil
      end

      if attributes.key?(:'default_ejs')
        self.default_ejs = attributes[:'default_ejs']
      else
        self.default_ejs = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @email_template_id.nil?
        invalid_properties.push('invalid value for "email_template_id", email_template_id cannot be nil.')
      end

      if @default_test_data.nil?
        invalid_properties.push('invalid value for "default_test_data", default_test_data cannot be nil.')
      end

      if @default_translations_by_locale.nil?
        invalid_properties.push('invalid value for "default_translations_by_locale", default_translations_by_locale cannot be nil.')
      end

      if @default_ejs.nil?
        invalid_properties.push('invalid value for "default_ejs", default_ejs cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @email_template_id.nil?
      return false if @default_test_data.nil?
      return false if @default_translations_by_locale.nil?
      return false if @default_ejs.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] email_template_id Value to be assigned
    def email_template_id=(email_template_id)
      if email_template_id.nil?
        fail ArgumentError, 'email_template_id cannot be nil'
      end

      @email_template_id = email_template_id
    end

    # Custom attribute writer method with validation
    # @param [Object] default_test_data Value to be assigned
    def default_test_data=(default_test_data)
      if default_test_data.nil?
        fail ArgumentError, 'default_test_data cannot be nil'
      end

      @default_test_data = default_test_data
    end

    # Custom attribute writer method with validation
    # @param [Object] default_translations_by_locale Value to be assigned
    def default_translations_by_locale=(default_translations_by_locale)
      if default_translations_by_locale.nil?
        fail ArgumentError, 'default_translations_by_locale cannot be nil'
      end

      @default_translations_by_locale = default_translations_by_locale
    end

    # Custom attribute writer method with validation
    # @param [Object] default_ejs Value to be assigned
    def default_ejs=(default_ejs)
      if default_ejs.nil?
        fail ArgumentError, 'default_ejs cannot be nil'
      end

      @default_ejs = default_ejs
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          email_template_id == o.email_template_id &&
          default_test_data == o.default_test_data &&
          default_translations_by_locale == o.default_translations_by_locale &&
          default_ejs == o.default_ejs
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [email_template_id, default_test_data, default_translations_by_locale, default_ejs].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
