=begin
#fastcomments

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.19.0-SNAPSHOT

=end

require 'date'
require 'time'

module FastCommentsClient
  class EventLogEntry < ApiModelBase
    attr_accessor :_id

    attr_accessor :created_at

    attr_accessor :tenant_id

    attr_accessor :url_id

    attr_accessor :broadcast_id

    attr_accessor :data

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'_id' => :'_id',
        :'created_at' => :'createdAt',
        :'tenant_id' => :'tenantId',
        :'url_id' => :'urlId',
        :'broadcast_id' => :'broadcastId',
        :'data' => :'data'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'_id' => :'String',
        :'created_at' => :'Time',
        :'tenant_id' => :'String',
        :'url_id' => :'String',
        :'broadcast_id' => :'String',
        :'data' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `FastCommentsClient::EventLogEntry` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `FastCommentsClient::EventLogEntry`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'_id')
        self._id = attributes[:'_id']
      else
        self._id = nil
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      else
        self.created_at = nil
      end

      if attributes.key?(:'tenant_id')
        self.tenant_id = attributes[:'tenant_id']
      else
        self.tenant_id = nil
      end

      if attributes.key?(:'url_id')
        self.url_id = attributes[:'url_id']
      else
        self.url_id = nil
      end

      if attributes.key?(:'broadcast_id')
        self.broadcast_id = attributes[:'broadcast_id']
      else
        self.broadcast_id = nil
      end

      if attributes.key?(:'data')
        self.data = attributes[:'data']
      else
        self.data = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @_id.nil?
        invalid_properties.push('invalid value for "_id", _id cannot be nil.')
      end

      if @created_at.nil?
        invalid_properties.push('invalid value for "created_at", created_at cannot be nil.')
      end

      if @tenant_id.nil?
        invalid_properties.push('invalid value for "tenant_id", tenant_id cannot be nil.')
      end

      if @url_id.nil?
        invalid_properties.push('invalid value for "url_id", url_id cannot be nil.')
      end

      if @broadcast_id.nil?
        invalid_properties.push('invalid value for "broadcast_id", broadcast_id cannot be nil.')
      end

      if @data.nil?
        invalid_properties.push('invalid value for "data", data cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @_id.nil?
      return false if @created_at.nil?
      return false if @tenant_id.nil?
      return false if @url_id.nil?
      return false if @broadcast_id.nil?
      return false if @data.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] _id Value to be assigned
    def _id=(_id)
      if _id.nil?
        fail ArgumentError, '_id cannot be nil'
      end

      @_id = _id
    end

    # Custom attribute writer method with validation
    # @param [Object] created_at Value to be assigned
    def created_at=(created_at)
      if created_at.nil?
        fail ArgumentError, 'created_at cannot be nil'
      end

      @created_at = created_at
    end

    # Custom attribute writer method with validation
    # @param [Object] tenant_id Value to be assigned
    def tenant_id=(tenant_id)
      if tenant_id.nil?
        fail ArgumentError, 'tenant_id cannot be nil'
      end

      @tenant_id = tenant_id
    end

    # Custom attribute writer method with validation
    # @param [Object] url_id Value to be assigned
    def url_id=(url_id)
      if url_id.nil?
        fail ArgumentError, 'url_id cannot be nil'
      end

      @url_id = url_id
    end

    # Custom attribute writer method with validation
    # @param [Object] broadcast_id Value to be assigned
    def broadcast_id=(broadcast_id)
      if broadcast_id.nil?
        fail ArgumentError, 'broadcast_id cannot be nil'
      end

      @broadcast_id = broadcast_id
    end

    # Custom attribute writer method with validation
    # @param [Object] data Value to be assigned
    def data=(data)
      if data.nil?
        fail ArgumentError, 'data cannot be nil'
      end

      @data = data
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          _id == o._id &&
          created_at == o.created_at &&
          tenant_id == o.tenant_id &&
          url_id == o.url_id &&
          broadcast_id == o.broadcast_id &&
          data == o.data
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [_id, created_at, tenant_id, url_id, broadcast_id, data].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
