=begin
#fastcomments

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.18.0-SNAPSHOT

=end

require 'date'
require 'time'

module FastCommentsClient
  class FComment < ApiModelBase
    attr_accessor :_id

    attr_accessor :tenant_id

    attr_accessor :url_id

    attr_accessor :url_id_raw

    attr_accessor :url

    attr_accessor :page_title

    attr_accessor :user_id

    attr_accessor :anon_user_id

    attr_accessor :commenter_email

    attr_accessor :commenter_name

    attr_accessor :commenter_link

    attr_accessor :comment

    attr_accessor :comment_html

    attr_accessor :parent_id

    attr_accessor :date

    attr_accessor :local_date_string

    attr_accessor :local_date_hours

    attr_accessor :votes

    attr_accessor :votes_up

    attr_accessor :votes_down

    attr_accessor :expire_at

    attr_accessor :verified

    attr_accessor :verified_date

    attr_accessor :verification_id

    attr_accessor :notification_sent_for_parent

    attr_accessor :notification_sent_for_parent_tenant

    attr_accessor :reviewed

    attr_accessor :imported

    attr_accessor :external_id

    attr_accessor :external_parent_id

    attr_accessor :avatar_src

    attr_accessor :is_spam

    attr_accessor :perm_not_spam

    attr_accessor :ai_determined_spam

    attr_accessor :has_images

    attr_accessor :page_number

    attr_accessor :page_number_of

    attr_accessor :page_number_nf

    attr_accessor :has_links

    attr_accessor :has_code

    attr_accessor :approved

    attr_accessor :locale

    attr_accessor :is_deleted

    attr_accessor :is_deleted_user

    attr_accessor :is_banned_user

    attr_accessor :is_by_admin

    attr_accessor :is_by_moderator

    attr_accessor :is_pinned

    attr_accessor :is_locked

    attr_accessor :flag_count

    attr_accessor :rating

    attr_accessor :display_label

    attr_accessor :from_product_id

    attr_accessor :meta

    attr_accessor :ip_hash

    attr_accessor :mentions

    attr_accessor :hash_tags

    attr_accessor :badges

    attr_accessor :domain

    attr_accessor :veteran_badge_processed

    attr_accessor :moderation_group_ids

    attr_accessor :did_process_badges

    attr_accessor :from_offline_restore

    attr_accessor :autoplay_job_id

    attr_accessor :autoplay_delay_ms

    attr_accessor :feedback_ids

    attr_accessor :logs

    attr_accessor :group_ids

    attr_accessor :view_count

    attr_accessor :requires_verification

    attr_accessor :edit_key

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'_id' => :'_id',
        :'tenant_id' => :'tenantId',
        :'url_id' => :'urlId',
        :'url_id_raw' => :'urlIdRaw',
        :'url' => :'url',
        :'page_title' => :'pageTitle',
        :'user_id' => :'userId',
        :'anon_user_id' => :'anonUserId',
        :'commenter_email' => :'commenterEmail',
        :'commenter_name' => :'commenterName',
        :'commenter_link' => :'commenterLink',
        :'comment' => :'comment',
        :'comment_html' => :'commentHTML',
        :'parent_id' => :'parentId',
        :'date' => :'date',
        :'local_date_string' => :'localDateString',
        :'local_date_hours' => :'localDateHours',
        :'votes' => :'votes',
        :'votes_up' => :'votesUp',
        :'votes_down' => :'votesDown',
        :'expire_at' => :'expireAt',
        :'verified' => :'verified',
        :'verified_date' => :'verifiedDate',
        :'verification_id' => :'verificationId',
        :'notification_sent_for_parent' => :'notificationSentForParent',
        :'notification_sent_for_parent_tenant' => :'notificationSentForParentTenant',
        :'reviewed' => :'reviewed',
        :'imported' => :'imported',
        :'external_id' => :'externalId',
        :'external_parent_id' => :'externalParentId',
        :'avatar_src' => :'avatarSrc',
        :'is_spam' => :'isSpam',
        :'perm_not_spam' => :'permNotSpam',
        :'ai_determined_spam' => :'aiDeterminedSpam',
        :'has_images' => :'hasImages',
        :'page_number' => :'pageNumber',
        :'page_number_of' => :'pageNumberOF',
        :'page_number_nf' => :'pageNumberNF',
        :'has_links' => :'hasLinks',
        :'has_code' => :'hasCode',
        :'approved' => :'approved',
        :'locale' => :'locale',
        :'is_deleted' => :'isDeleted',
        :'is_deleted_user' => :'isDeletedUser',
        :'is_banned_user' => :'isBannedUser',
        :'is_by_admin' => :'isByAdmin',
        :'is_by_moderator' => :'isByModerator',
        :'is_pinned' => :'isPinned',
        :'is_locked' => :'isLocked',
        :'flag_count' => :'flagCount',
        :'rating' => :'rating',
        :'display_label' => :'displayLabel',
        :'from_product_id' => :'fromProductId',
        :'meta' => :'meta',
        :'ip_hash' => :'ipHash',
        :'mentions' => :'mentions',
        :'hash_tags' => :'hashTags',
        :'badges' => :'badges',
        :'domain' => :'domain',
        :'veteran_badge_processed' => :'veteranBadgeProcessed',
        :'moderation_group_ids' => :'moderationGroupIds',
        :'did_process_badges' => :'didProcessBadges',
        :'from_offline_restore' => :'fromOfflineRestore',
        :'autoplay_job_id' => :'autoplayJobId',
        :'autoplay_delay_ms' => :'autoplayDelayMS',
        :'feedback_ids' => :'feedbackIds',
        :'logs' => :'logs',
        :'group_ids' => :'groupIds',
        :'view_count' => :'viewCount',
        :'requires_verification' => :'requiresVerification',
        :'edit_key' => :'editKey'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'_id' => :'String',
        :'tenant_id' => :'String',
        :'url_id' => :'String',
        :'url_id_raw' => :'String',
        :'url' => :'String',
        :'page_title' => :'String',
        :'user_id' => :'String',
        :'anon_user_id' => :'String',
        :'commenter_email' => :'String',
        :'commenter_name' => :'String',
        :'commenter_link' => :'String',
        :'comment' => :'String',
        :'comment_html' => :'String',
        :'parent_id' => :'String',
        :'date' => :'Time',
        :'local_date_string' => :'String',
        :'local_date_hours' => :'Integer',
        :'votes' => :'Integer',
        :'votes_up' => :'Integer',
        :'votes_down' => :'Integer',
        :'expire_at' => :'Time',
        :'verified' => :'Boolean',
        :'verified_date' => :'Time',
        :'verification_id' => :'String',
        :'notification_sent_for_parent' => :'Boolean',
        :'notification_sent_for_parent_tenant' => :'Boolean',
        :'reviewed' => :'Boolean',
        :'imported' => :'Boolean',
        :'external_id' => :'String',
        :'external_parent_id' => :'String',
        :'avatar_src' => :'String',
        :'is_spam' => :'Boolean',
        :'perm_not_spam' => :'Boolean',
        :'ai_determined_spam' => :'Boolean',
        :'has_images' => :'Boolean',
        :'page_number' => :'Integer',
        :'page_number_of' => :'Integer',
        :'page_number_nf' => :'Integer',
        :'has_links' => :'Boolean',
        :'has_code' => :'Boolean',
        :'approved' => :'Boolean',
        :'locale' => :'String',
        :'is_deleted' => :'Boolean',
        :'is_deleted_user' => :'Boolean',
        :'is_banned_user' => :'Boolean',
        :'is_by_admin' => :'Boolean',
        :'is_by_moderator' => :'Boolean',
        :'is_pinned' => :'Boolean',
        :'is_locked' => :'Boolean',
        :'flag_count' => :'Integer',
        :'rating' => :'Float',
        :'display_label' => :'String',
        :'from_product_id' => :'Integer',
        :'meta' => :'FCommentMeta',
        :'ip_hash' => :'String',
        :'mentions' => :'Array<CommentUserMentionInfo>',
        :'hash_tags' => :'Array<CommentUserHashTagInfo>',
        :'badges' => :'Array<CommentUserBadgeInfo>',
        :'domain' => :'String',
        :'veteran_badge_processed' => :'String',
        :'moderation_group_ids' => :'Array<String>',
        :'did_process_badges' => :'Boolean',
        :'from_offline_restore' => :'Boolean',
        :'autoplay_job_id' => :'String',
        :'autoplay_delay_ms' => :'Integer',
        :'feedback_ids' => :'Array<String>',
        :'logs' => :'Array<CommentLogEntry>',
        :'group_ids' => :'Array<String>',
        :'view_count' => :'Integer',
        :'requires_verification' => :'Boolean',
        :'edit_key' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'page_title',
        :'user_id',
        :'anon_user_id',
        :'commenter_email',
        :'commenter_link',
        :'parent_id',
        :'date',
        :'local_date_string',
        :'local_date_hours',
        :'votes',
        :'votes_up',
        :'votes_down',
        :'expire_at',
        :'verified_date',
        :'verification_id',
        :'external_parent_id',
        :'avatar_src',
        :'page_number',
        :'page_number_of',
        :'page_number_nf',
        :'locale',
        :'is_pinned',
        :'is_locked',
        :'flag_count',
        :'rating',
        :'display_label',
        :'meta',
        :'badges',
        :'domain',
        :'moderation_group_ids',
        :'logs',
        :'group_ids',
        :'view_count',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `FastCommentsClient::FComment` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `FastCommentsClient::FComment`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'_id')
        self._id = attributes[:'_id']
      else
        self._id = nil
      end

      if attributes.key?(:'tenant_id')
        self.tenant_id = attributes[:'tenant_id']
      else
        self.tenant_id = nil
      end

      if attributes.key?(:'url_id')
        self.url_id = attributes[:'url_id']
      else
        self.url_id = nil
      end

      if attributes.key?(:'url_id_raw')
        self.url_id_raw = attributes[:'url_id_raw']
      end

      if attributes.key?(:'url')
        self.url = attributes[:'url']
      else
        self.url = nil
      end

      if attributes.key?(:'page_title')
        self.page_title = attributes[:'page_title']
      end

      if attributes.key?(:'user_id')
        self.user_id = attributes[:'user_id']
      end

      if attributes.key?(:'anon_user_id')
        self.anon_user_id = attributes[:'anon_user_id']
      end

      if attributes.key?(:'commenter_email')
        self.commenter_email = attributes[:'commenter_email']
      end

      if attributes.key?(:'commenter_name')
        self.commenter_name = attributes[:'commenter_name']
      else
        self.commenter_name = nil
      end

      if attributes.key?(:'commenter_link')
        self.commenter_link = attributes[:'commenter_link']
      end

      if attributes.key?(:'comment')
        self.comment = attributes[:'comment']
      else
        self.comment = nil
      end

      if attributes.key?(:'comment_html')
        self.comment_html = attributes[:'comment_html']
      else
        self.comment_html = nil
      end

      if attributes.key?(:'parent_id')
        self.parent_id = attributes[:'parent_id']
      end

      if attributes.key?(:'date')
        self.date = attributes[:'date']
      else
        self.date = nil
      end

      if attributes.key?(:'local_date_string')
        self.local_date_string = attributes[:'local_date_string']
      end

      if attributes.key?(:'local_date_hours')
        self.local_date_hours = attributes[:'local_date_hours']
      end

      if attributes.key?(:'votes')
        self.votes = attributes[:'votes']
      end

      if attributes.key?(:'votes_up')
        self.votes_up = attributes[:'votes_up']
      end

      if attributes.key?(:'votes_down')
        self.votes_down = attributes[:'votes_down']
      end

      if attributes.key?(:'expire_at')
        self.expire_at = attributes[:'expire_at']
      end

      if attributes.key?(:'verified')
        self.verified = attributes[:'verified']
      else
        self.verified = nil
      end

      if attributes.key?(:'verified_date')
        self.verified_date = attributes[:'verified_date']
      end

      if attributes.key?(:'verification_id')
        self.verification_id = attributes[:'verification_id']
      end

      if attributes.key?(:'notification_sent_for_parent')
        self.notification_sent_for_parent = attributes[:'notification_sent_for_parent']
      end

      if attributes.key?(:'notification_sent_for_parent_tenant')
        self.notification_sent_for_parent_tenant = attributes[:'notification_sent_for_parent_tenant']
      end

      if attributes.key?(:'reviewed')
        self.reviewed = attributes[:'reviewed']
      end

      if attributes.key?(:'imported')
        self.imported = attributes[:'imported']
      end

      if attributes.key?(:'external_id')
        self.external_id = attributes[:'external_id']
      end

      if attributes.key?(:'external_parent_id')
        self.external_parent_id = attributes[:'external_parent_id']
      end

      if attributes.key?(:'avatar_src')
        self.avatar_src = attributes[:'avatar_src']
      end

      if attributes.key?(:'is_spam')
        self.is_spam = attributes[:'is_spam']
      end

      if attributes.key?(:'perm_not_spam')
        self.perm_not_spam = attributes[:'perm_not_spam']
      end

      if attributes.key?(:'ai_determined_spam')
        self.ai_determined_spam = attributes[:'ai_determined_spam']
      end

      if attributes.key?(:'has_images')
        self.has_images = attributes[:'has_images']
      end

      if attributes.key?(:'page_number')
        self.page_number = attributes[:'page_number']
      end

      if attributes.key?(:'page_number_of')
        self.page_number_of = attributes[:'page_number_of']
      end

      if attributes.key?(:'page_number_nf')
        self.page_number_nf = attributes[:'page_number_nf']
      end

      if attributes.key?(:'has_links')
        self.has_links = attributes[:'has_links']
      end

      if attributes.key?(:'has_code')
        self.has_code = attributes[:'has_code']
      end

      if attributes.key?(:'approved')
        self.approved = attributes[:'approved']
      else
        self.approved = nil
      end

      if attributes.key?(:'locale')
        self.locale = attributes[:'locale']
      else
        self.locale = nil
      end

      if attributes.key?(:'is_deleted')
        self.is_deleted = attributes[:'is_deleted']
      end

      if attributes.key?(:'is_deleted_user')
        self.is_deleted_user = attributes[:'is_deleted_user']
      end

      if attributes.key?(:'is_banned_user')
        self.is_banned_user = attributes[:'is_banned_user']
      end

      if attributes.key?(:'is_by_admin')
        self.is_by_admin = attributes[:'is_by_admin']
      end

      if attributes.key?(:'is_by_moderator')
        self.is_by_moderator = attributes[:'is_by_moderator']
      end

      if attributes.key?(:'is_pinned')
        self.is_pinned = attributes[:'is_pinned']
      end

      if attributes.key?(:'is_locked')
        self.is_locked = attributes[:'is_locked']
      end

      if attributes.key?(:'flag_count')
        self.flag_count = attributes[:'flag_count']
      end

      if attributes.key?(:'rating')
        self.rating = attributes[:'rating']
      end

      if attributes.key?(:'display_label')
        self.display_label = attributes[:'display_label']
      end

      if attributes.key?(:'from_product_id')
        self.from_product_id = attributes[:'from_product_id']
      end

      if attributes.key?(:'meta')
        self.meta = attributes[:'meta']
      end

      if attributes.key?(:'ip_hash')
        self.ip_hash = attributes[:'ip_hash']
      end

      if attributes.key?(:'mentions')
        if (value = attributes[:'mentions']).is_a?(Array)
          self.mentions = value
        end
      end

      if attributes.key?(:'hash_tags')
        if (value = attributes[:'hash_tags']).is_a?(Array)
          self.hash_tags = value
        end
      end

      if attributes.key?(:'badges')
        if (value = attributes[:'badges']).is_a?(Array)
          self.badges = value
        end
      end

      if attributes.key?(:'domain')
        self.domain = attributes[:'domain']
      end

      if attributes.key?(:'veteran_badge_processed')
        self.veteran_badge_processed = attributes[:'veteran_badge_processed']
      end

      if attributes.key?(:'moderation_group_ids')
        if (value = attributes[:'moderation_group_ids']).is_a?(Array)
          self.moderation_group_ids = value
        end
      end

      if attributes.key?(:'did_process_badges')
        self.did_process_badges = attributes[:'did_process_badges']
      end

      if attributes.key?(:'from_offline_restore')
        self.from_offline_restore = attributes[:'from_offline_restore']
      end

      if attributes.key?(:'autoplay_job_id')
        self.autoplay_job_id = attributes[:'autoplay_job_id']
      end

      if attributes.key?(:'autoplay_delay_ms')
        self.autoplay_delay_ms = attributes[:'autoplay_delay_ms']
      end

      if attributes.key?(:'feedback_ids')
        if (value = attributes[:'feedback_ids']).is_a?(Array)
          self.feedback_ids = value
        end
      end

      if attributes.key?(:'logs')
        if (value = attributes[:'logs']).is_a?(Array)
          self.logs = value
        end
      end

      if attributes.key?(:'group_ids')
        if (value = attributes[:'group_ids']).is_a?(Array)
          self.group_ids = value
        end
      end

      if attributes.key?(:'view_count')
        self.view_count = attributes[:'view_count']
      end

      if attributes.key?(:'requires_verification')
        self.requires_verification = attributes[:'requires_verification']
      end

      if attributes.key?(:'edit_key')
        self.edit_key = attributes[:'edit_key']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @_id.nil?
        invalid_properties.push('invalid value for "_id", _id cannot be nil.')
      end

      if @tenant_id.nil?
        invalid_properties.push('invalid value for "tenant_id", tenant_id cannot be nil.')
      end

      if @url_id.nil?
        invalid_properties.push('invalid value for "url_id", url_id cannot be nil.')
      end

      if @url.nil?
        invalid_properties.push('invalid value for "url", url cannot be nil.')
      end

      if @commenter_name.nil?
        invalid_properties.push('invalid value for "commenter_name", commenter_name cannot be nil.')
      end

      if @comment.nil?
        invalid_properties.push('invalid value for "comment", comment cannot be nil.')
      end

      if @comment_html.nil?
        invalid_properties.push('invalid value for "comment_html", comment_html cannot be nil.')
      end

      if @verified.nil?
        invalid_properties.push('invalid value for "verified", verified cannot be nil.')
      end

      if @approved.nil?
        invalid_properties.push('invalid value for "approved", approved cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @_id.nil?
      return false if @tenant_id.nil?
      return false if @url_id.nil?
      return false if @url.nil?
      return false if @commenter_name.nil?
      return false if @comment.nil?
      return false if @comment_html.nil?
      return false if @verified.nil?
      return false if @approved.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] _id Value to be assigned
    def _id=(_id)
      if _id.nil?
        fail ArgumentError, '_id cannot be nil'
      end

      @_id = _id
    end

    # Custom attribute writer method with validation
    # @param [Object] tenant_id Value to be assigned
    def tenant_id=(tenant_id)
      if tenant_id.nil?
        fail ArgumentError, 'tenant_id cannot be nil'
      end

      @tenant_id = tenant_id
    end

    # Custom attribute writer method with validation
    # @param [Object] url_id Value to be assigned
    def url_id=(url_id)
      if url_id.nil?
        fail ArgumentError, 'url_id cannot be nil'
      end

      @url_id = url_id
    end

    # Custom attribute writer method with validation
    # @param [Object] url Value to be assigned
    def url=(url)
      if url.nil?
        fail ArgumentError, 'url cannot be nil'
      end

      @url = url
    end

    # Custom attribute writer method with validation
    # @param [Object] commenter_name Value to be assigned
    def commenter_name=(commenter_name)
      if commenter_name.nil?
        fail ArgumentError, 'commenter_name cannot be nil'
      end

      @commenter_name = commenter_name
    end

    # Custom attribute writer method with validation
    # @param [Object] comment Value to be assigned
    def comment=(comment)
      if comment.nil?
        fail ArgumentError, 'comment cannot be nil'
      end

      @comment = comment
    end

    # Custom attribute writer method with validation
    # @param [Object] comment_html Value to be assigned
    def comment_html=(comment_html)
      if comment_html.nil?
        fail ArgumentError, 'comment_html cannot be nil'
      end

      @comment_html = comment_html
    end

    # Custom attribute writer method with validation
    # @param [Object] verified Value to be assigned
    def verified=(verified)
      if verified.nil?
        fail ArgumentError, 'verified cannot be nil'
      end

      @verified = verified
    end

    # Custom attribute writer method with validation
    # @param [Object] approved Value to be assigned
    def approved=(approved)
      if approved.nil?
        fail ArgumentError, 'approved cannot be nil'
      end

      @approved = approved
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          _id == o._id &&
          tenant_id == o.tenant_id &&
          url_id == o.url_id &&
          url_id_raw == o.url_id_raw &&
          url == o.url &&
          page_title == o.page_title &&
          user_id == o.user_id &&
          anon_user_id == o.anon_user_id &&
          commenter_email == o.commenter_email &&
          commenter_name == o.commenter_name &&
          commenter_link == o.commenter_link &&
          comment == o.comment &&
          comment_html == o.comment_html &&
          parent_id == o.parent_id &&
          date == o.date &&
          local_date_string == o.local_date_string &&
          local_date_hours == o.local_date_hours &&
          votes == o.votes &&
          votes_up == o.votes_up &&
          votes_down == o.votes_down &&
          expire_at == o.expire_at &&
          verified == o.verified &&
          verified_date == o.verified_date &&
          verification_id == o.verification_id &&
          notification_sent_for_parent == o.notification_sent_for_parent &&
          notification_sent_for_parent_tenant == o.notification_sent_for_parent_tenant &&
          reviewed == o.reviewed &&
          imported == o.imported &&
          external_id == o.external_id &&
          external_parent_id == o.external_parent_id &&
          avatar_src == o.avatar_src &&
          is_spam == o.is_spam &&
          perm_not_spam == o.perm_not_spam &&
          ai_determined_spam == o.ai_determined_spam &&
          has_images == o.has_images &&
          page_number == o.page_number &&
          page_number_of == o.page_number_of &&
          page_number_nf == o.page_number_nf &&
          has_links == o.has_links &&
          has_code == o.has_code &&
          approved == o.approved &&
          locale == o.locale &&
          is_deleted == o.is_deleted &&
          is_deleted_user == o.is_deleted_user &&
          is_banned_user == o.is_banned_user &&
          is_by_admin == o.is_by_admin &&
          is_by_moderator == o.is_by_moderator &&
          is_pinned == o.is_pinned &&
          is_locked == o.is_locked &&
          flag_count == o.flag_count &&
          rating == o.rating &&
          display_label == o.display_label &&
          from_product_id == o.from_product_id &&
          meta == o.meta &&
          ip_hash == o.ip_hash &&
          mentions == o.mentions &&
          hash_tags == o.hash_tags &&
          badges == o.badges &&
          domain == o.domain &&
          veteran_badge_processed == o.veteran_badge_processed &&
          moderation_group_ids == o.moderation_group_ids &&
          did_process_badges == o.did_process_badges &&
          from_offline_restore == o.from_offline_restore &&
          autoplay_job_id == o.autoplay_job_id &&
          autoplay_delay_ms == o.autoplay_delay_ms &&
          feedback_ids == o.feedback_ids &&
          logs == o.logs &&
          group_ids == o.group_ids &&
          view_count == o.view_count &&
          requires_verification == o.requires_verification &&
          edit_key == o.edit_key
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [_id, tenant_id, url_id, url_id_raw, url, page_title, user_id, anon_user_id, commenter_email, commenter_name, commenter_link, comment, comment_html, parent_id, date, local_date_string, local_date_hours, votes, votes_up, votes_down, expire_at, verified, verified_date, verification_id, notification_sent_for_parent, notification_sent_for_parent_tenant, reviewed, imported, external_id, external_parent_id, avatar_src, is_spam, perm_not_spam, ai_determined_spam, has_images, page_number, page_number_of, page_number_nf, has_links, has_code, approved, locale, is_deleted, is_deleted_user, is_banned_user, is_by_admin, is_by_moderator, is_pinned, is_locked, flag_count, rating, display_label, from_product_id, meta, ip_hash, mentions, hash_tags, badges, domain, veteran_badge_processed, moderation_group_ids, did_process_badges, from_offline_restore, autoplay_job_id, autoplay_delay_ms, feedback_ids, logs, group_ids, view_count, requires_verification, edit_key].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
