=begin
#fastcomments

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'date'
require 'time'

module FastCommentsClient
  class GetUserInternalProfileResponseProfile
    attr_accessor :commenter_name

    attr_accessor :first_comment_date

    attr_accessor :ip_hash

    attr_accessor :country_flag

    attr_accessor :country_code

    attr_accessor :website_url

    attr_accessor :bio

    attr_accessor :karma

    attr_accessor :locale

    attr_accessor :verified

    attr_accessor :avatar_src

    attr_accessor :display_name

    attr_accessor :username

    attr_accessor :commenter_email

    attr_accessor :email

    attr_accessor :anon_user_id

    attr_accessor :user_id

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'commenter_name' => :'commenterName',
        :'first_comment_date' => :'firstCommentDate',
        :'ip_hash' => :'ipHash',
        :'country_flag' => :'countryFlag',
        :'country_code' => :'countryCode',
        :'website_url' => :'websiteUrl',
        :'bio' => :'bio',
        :'karma' => :'karma',
        :'locale' => :'locale',
        :'verified' => :'verified',
        :'avatar_src' => :'avatarSrc',
        :'display_name' => :'displayName',
        :'username' => :'username',
        :'commenter_email' => :'commenterEmail',
        :'email' => :'email',
        :'anon_user_id' => :'anonUserId',
        :'user_id' => :'userId'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'commenter_name' => :'String',
        :'first_comment_date' => :'Time',
        :'ip_hash' => :'String',
        :'country_flag' => :'String',
        :'country_code' => :'String',
        :'website_url' => :'String',
        :'bio' => :'String',
        :'karma' => :'Float',
        :'locale' => :'String',
        :'verified' => :'Boolean',
        :'avatar_src' => :'String',
        :'display_name' => :'String',
        :'username' => :'String',
        :'commenter_email' => :'String',
        :'email' => :'String',
        :'anon_user_id' => :'String',
        :'user_id' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'first_comment_date',
        :'website_url',
        :'avatar_src',
        :'commenter_email',
        :'email',
        :'anon_user_id',
        :'user_id'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `FastCommentsClient::GetUserInternalProfileResponseProfile` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `FastCommentsClient::GetUserInternalProfileResponseProfile`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'commenter_name')
        self.commenter_name = attributes[:'commenter_name']
      end

      if attributes.key?(:'first_comment_date')
        self.first_comment_date = attributes[:'first_comment_date']
      end

      if attributes.key?(:'ip_hash')
        self.ip_hash = attributes[:'ip_hash']
      end

      if attributes.key?(:'country_flag')
        self.country_flag = attributes[:'country_flag']
      end

      if attributes.key?(:'country_code')
        self.country_code = attributes[:'country_code']
      end

      if attributes.key?(:'website_url')
        self.website_url = attributes[:'website_url']
      end

      if attributes.key?(:'bio')
        self.bio = attributes[:'bio']
      end

      if attributes.key?(:'karma')
        self.karma = attributes[:'karma']
      end

      if attributes.key?(:'locale')
        self.locale = attributes[:'locale']
      end

      if attributes.key?(:'verified')
        self.verified = attributes[:'verified']
      end

      if attributes.key?(:'avatar_src')
        self.avatar_src = attributes[:'avatar_src']
      end

      if attributes.key?(:'display_name')
        self.display_name = attributes[:'display_name']
      end

      if attributes.key?(:'username')
        self.username = attributes[:'username']
      end

      if attributes.key?(:'commenter_email')
        self.commenter_email = attributes[:'commenter_email']
      end

      if attributes.key?(:'email')
        self.email = attributes[:'email']
      end

      if attributes.key?(:'anon_user_id')
        self.anon_user_id = attributes[:'anon_user_id']
      end

      if attributes.key?(:'user_id')
        self.user_id = attributes[:'user_id']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          commenter_name == o.commenter_name &&
          first_comment_date == o.first_comment_date &&
          ip_hash == o.ip_hash &&
          country_flag == o.country_flag &&
          country_code == o.country_code &&
          website_url == o.website_url &&
          bio == o.bio &&
          karma == o.karma &&
          locale == o.locale &&
          verified == o.verified &&
          avatar_src == o.avatar_src &&
          display_name == o.display_name &&
          username == o.username &&
          commenter_email == o.commenter_email &&
          email == o.email &&
          anon_user_id == o.anon_user_id &&
          user_id == o.user_id
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [commenter_name, first_comment_date, ip_hash, country_flag, country_code, website_url, bio, karma, locale, verified, avatar_src, display_name, username, commenter_email, email, anon_user_id, user_id].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = FastCommentsClient.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
