=begin
#fastcomments

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'date'
require 'time'

module FastCommentsClient
  class ModerationFilter
    attr_accessor :reviewed

    attr_accessor :approved

    attr_accessor :is_spam

    attr_accessor :is_banned_user

    attr_accessor :is_locked

    attr_accessor :flag_count_gt

    attr_accessor :user_id

    attr_accessor :url_id

    attr_accessor :domain

    attr_accessor :moderation_group_ids

    # Text search terms. Each term is matched case-insensitively against the comment text. A term wrapped in quotes means exact phrase match.
    attr_accessor :comment_text_search

    # Set by the `exact=\"...\"` search syntax. The comment text must equal this value exactly (case-sensitive, full-string), as opposed to the substring matching of commentTextSearch.
    attr_accessor :exact_comment_text

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'reviewed' => :'reviewed',
        :'approved' => :'approved',
        :'is_spam' => :'isSpam',
        :'is_banned_user' => :'isBannedUser',
        :'is_locked' => :'isLocked',
        :'flag_count_gt' => :'flagCountGt',
        :'user_id' => :'userId',
        :'url_id' => :'urlId',
        :'domain' => :'domain',
        :'moderation_group_ids' => :'moderationGroupIds',
        :'comment_text_search' => :'commentTextSearch',
        :'exact_comment_text' => :'exactCommentText'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'reviewed' => :'Boolean',
        :'approved' => :'Boolean',
        :'is_spam' => :'Boolean',
        :'is_banned_user' => :'Boolean',
        :'is_locked' => :'Boolean',
        :'flag_count_gt' => :'Float',
        :'user_id' => :'String',
        :'url_id' => :'String',
        :'domain' => :'String',
        :'moderation_group_ids' => :'Array<String>',
        :'comment_text_search' => :'Array<String>',
        :'exact_comment_text' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `FastCommentsClient::ModerationFilter` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `FastCommentsClient::ModerationFilter`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'reviewed')
        self.reviewed = attributes[:'reviewed']
      end

      if attributes.key?(:'approved')
        self.approved = attributes[:'approved']
      end

      if attributes.key?(:'is_spam')
        self.is_spam = attributes[:'is_spam']
      end

      if attributes.key?(:'is_banned_user')
        self.is_banned_user = attributes[:'is_banned_user']
      end

      if attributes.key?(:'is_locked')
        self.is_locked = attributes[:'is_locked']
      end

      if attributes.key?(:'flag_count_gt')
        self.flag_count_gt = attributes[:'flag_count_gt']
      end

      if attributes.key?(:'user_id')
        self.user_id = attributes[:'user_id']
      end

      if attributes.key?(:'url_id')
        self.url_id = attributes[:'url_id']
      end

      if attributes.key?(:'domain')
        self.domain = attributes[:'domain']
      end

      if attributes.key?(:'moderation_group_ids')
        if (value = attributes[:'moderation_group_ids']).is_a?(Array)
          self.moderation_group_ids = value
        end
      end

      if attributes.key?(:'comment_text_search')
        if (value = attributes[:'comment_text_search']).is_a?(Array)
          self.comment_text_search = value
        end
      end

      if attributes.key?(:'exact_comment_text')
        self.exact_comment_text = attributes[:'exact_comment_text']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          reviewed == o.reviewed &&
          approved == o.approved &&
          is_spam == o.is_spam &&
          is_banned_user == o.is_banned_user &&
          is_locked == o.is_locked &&
          flag_count_gt == o.flag_count_gt &&
          user_id == o.user_id &&
          url_id == o.url_id &&
          domain == o.domain &&
          moderation_group_ids == o.moderation_group_ids &&
          comment_text_search == o.comment_text_search &&
          exact_comment_text == o.exact_comment_text
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [reviewed, approved, is_spam, is_banned_user, is_locked, flag_count_gt, user_id, url_id, domain, moderation_group_ids, comment_text_search, exact_comment_text].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = FastCommentsClient.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
