=begin
#fastcomments

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0-SNAPSHOT

=end

require 'date'
require 'time'

module FastCommentsClient
  class ModerationAPIComment < ApiModelBase
    attr_accessor :is_local_deleted

    attr_accessor :reply_count

    attr_accessor :feedback_results

    attr_accessor :is_voted_up

    attr_accessor :is_voted_down

    attr_accessor :my_vote_id

    attr_accessor :_id

    attr_accessor :tenant_id

    attr_accessor :url_id

    attr_accessor :url

    attr_accessor :page_title

    attr_accessor :user_id

    attr_accessor :anon_user_id

    attr_accessor :commenter_name

    attr_accessor :commenter_link

    attr_accessor :comment_html

    attr_accessor :parent_id

    attr_accessor :date

    attr_accessor :local_date_string

    attr_accessor :votes

    attr_accessor :votes_up

    attr_accessor :votes_down

    attr_accessor :expire_at

    attr_accessor :reviewed

    attr_accessor :avatar_src

    attr_accessor :is_spam

    attr_accessor :perm_not_spam

    attr_accessor :has_links

    attr_accessor :has_code

    attr_accessor :approved

    attr_accessor :locale

    attr_accessor :is_banned_user

    attr_accessor :is_by_admin

    attr_accessor :is_by_moderator

    attr_accessor :is_pinned

    attr_accessor :is_locked

    attr_accessor :flag_count

    attr_accessor :display_label

    attr_accessor :badges

    attr_accessor :verified

    attr_accessor :feedback_ids

    attr_accessor :is_deleted

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'is_local_deleted' => :'isLocalDeleted',
        :'reply_count' => :'replyCount',
        :'feedback_results' => :'feedbackResults',
        :'is_voted_up' => :'isVotedUp',
        :'is_voted_down' => :'isVotedDown',
        :'my_vote_id' => :'myVoteId',
        :'_id' => :'_id',
        :'tenant_id' => :'tenantId',
        :'url_id' => :'urlId',
        :'url' => :'url',
        :'page_title' => :'pageTitle',
        :'user_id' => :'userId',
        :'anon_user_id' => :'anonUserId',
        :'commenter_name' => :'commenterName',
        :'commenter_link' => :'commenterLink',
        :'comment_html' => :'commentHTML',
        :'parent_id' => :'parentId',
        :'date' => :'date',
        :'local_date_string' => :'localDateString',
        :'votes' => :'votes',
        :'votes_up' => :'votesUp',
        :'votes_down' => :'votesDown',
        :'expire_at' => :'expireAt',
        :'reviewed' => :'reviewed',
        :'avatar_src' => :'avatarSrc',
        :'is_spam' => :'isSpam',
        :'perm_not_spam' => :'permNotSpam',
        :'has_links' => :'hasLinks',
        :'has_code' => :'hasCode',
        :'approved' => :'approved',
        :'locale' => :'locale',
        :'is_banned_user' => :'isBannedUser',
        :'is_by_admin' => :'isByAdmin',
        :'is_by_moderator' => :'isByModerator',
        :'is_pinned' => :'isPinned',
        :'is_locked' => :'isLocked',
        :'flag_count' => :'flagCount',
        :'display_label' => :'displayLabel',
        :'badges' => :'badges',
        :'verified' => :'verified',
        :'feedback_ids' => :'feedbackIds',
        :'is_deleted' => :'isDeleted'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'is_local_deleted' => :'Boolean',
        :'reply_count' => :'Float',
        :'feedback_results' => :'Array<String>',
        :'is_voted_up' => :'Boolean',
        :'is_voted_down' => :'Boolean',
        :'my_vote_id' => :'String',
        :'_id' => :'String',
        :'tenant_id' => :'String',
        :'url_id' => :'String',
        :'url' => :'String',
        :'page_title' => :'String',
        :'user_id' => :'String',
        :'anon_user_id' => :'String',
        :'commenter_name' => :'String',
        :'commenter_link' => :'String',
        :'comment_html' => :'String',
        :'parent_id' => :'String',
        :'date' => :'Time',
        :'local_date_string' => :'String',
        :'votes' => :'Float',
        :'votes_up' => :'Float',
        :'votes_down' => :'Float',
        :'expire_at' => :'Time',
        :'reviewed' => :'Boolean',
        :'avatar_src' => :'String',
        :'is_spam' => :'Boolean',
        :'perm_not_spam' => :'Boolean',
        :'has_links' => :'Boolean',
        :'has_code' => :'Boolean',
        :'approved' => :'Boolean',
        :'locale' => :'String',
        :'is_banned_user' => :'Boolean',
        :'is_by_admin' => :'Boolean',
        :'is_by_moderator' => :'Boolean',
        :'is_pinned' => :'Boolean',
        :'is_locked' => :'Boolean',
        :'flag_count' => :'Float',
        :'display_label' => :'String',
        :'badges' => :'Array<CommentUserBadgeInfo>',
        :'verified' => :'Boolean',
        :'feedback_ids' => :'Array<String>',
        :'is_deleted' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'page_title',
        :'user_id',
        :'anon_user_id',
        :'commenter_link',
        :'parent_id',
        :'date',
        :'local_date_string',
        :'votes',
        :'votes_up',
        :'votes_down',
        :'expire_at',
        :'avatar_src',
        :'locale',
        :'is_pinned',
        :'is_locked',
        :'flag_count',
        :'display_label',
        :'badges',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `FastCommentsClient::ModerationAPIComment` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `FastCommentsClient::ModerationAPIComment`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'is_local_deleted')
        self.is_local_deleted = attributes[:'is_local_deleted']
      end

      if attributes.key?(:'reply_count')
        self.reply_count = attributes[:'reply_count']
      end

      if attributes.key?(:'feedback_results')
        if (value = attributes[:'feedback_results']).is_a?(Array)
          self.feedback_results = value
        end
      end

      if attributes.key?(:'is_voted_up')
        self.is_voted_up = attributes[:'is_voted_up']
      end

      if attributes.key?(:'is_voted_down')
        self.is_voted_down = attributes[:'is_voted_down']
      end

      if attributes.key?(:'my_vote_id')
        self.my_vote_id = attributes[:'my_vote_id']
      end

      if attributes.key?(:'_id')
        self._id = attributes[:'_id']
      else
        self._id = nil
      end

      if attributes.key?(:'tenant_id')
        self.tenant_id = attributes[:'tenant_id']
      else
        self.tenant_id = nil
      end

      if attributes.key?(:'url_id')
        self.url_id = attributes[:'url_id']
      else
        self.url_id = nil
      end

      if attributes.key?(:'url')
        self.url = attributes[:'url']
      else
        self.url = nil
      end

      if attributes.key?(:'page_title')
        self.page_title = attributes[:'page_title']
      end

      if attributes.key?(:'user_id')
        self.user_id = attributes[:'user_id']
      end

      if attributes.key?(:'anon_user_id')
        self.anon_user_id = attributes[:'anon_user_id']
      end

      if attributes.key?(:'commenter_name')
        self.commenter_name = attributes[:'commenter_name']
      else
        self.commenter_name = nil
      end

      if attributes.key?(:'commenter_link')
        self.commenter_link = attributes[:'commenter_link']
      end

      if attributes.key?(:'comment_html')
        self.comment_html = attributes[:'comment_html']
      else
        self.comment_html = nil
      end

      if attributes.key?(:'parent_id')
        self.parent_id = attributes[:'parent_id']
      end

      if attributes.key?(:'date')
        self.date = attributes[:'date']
      else
        self.date = nil
      end

      if attributes.key?(:'local_date_string')
        self.local_date_string = attributes[:'local_date_string']
      end

      if attributes.key?(:'votes')
        self.votes = attributes[:'votes']
      end

      if attributes.key?(:'votes_up')
        self.votes_up = attributes[:'votes_up']
      end

      if attributes.key?(:'votes_down')
        self.votes_down = attributes[:'votes_down']
      end

      if attributes.key?(:'expire_at')
        self.expire_at = attributes[:'expire_at']
      end

      if attributes.key?(:'reviewed')
        self.reviewed = attributes[:'reviewed']
      end

      if attributes.key?(:'avatar_src')
        self.avatar_src = attributes[:'avatar_src']
      end

      if attributes.key?(:'is_spam')
        self.is_spam = attributes[:'is_spam']
      end

      if attributes.key?(:'perm_not_spam')
        self.perm_not_spam = attributes[:'perm_not_spam']
      end

      if attributes.key?(:'has_links')
        self.has_links = attributes[:'has_links']
      end

      if attributes.key?(:'has_code')
        self.has_code = attributes[:'has_code']
      end

      if attributes.key?(:'approved')
        self.approved = attributes[:'approved']
      else
        self.approved = nil
      end

      if attributes.key?(:'locale')
        self.locale = attributes[:'locale']
      else
        self.locale = nil
      end

      if attributes.key?(:'is_banned_user')
        self.is_banned_user = attributes[:'is_banned_user']
      end

      if attributes.key?(:'is_by_admin')
        self.is_by_admin = attributes[:'is_by_admin']
      end

      if attributes.key?(:'is_by_moderator')
        self.is_by_moderator = attributes[:'is_by_moderator']
      end

      if attributes.key?(:'is_pinned')
        self.is_pinned = attributes[:'is_pinned']
      end

      if attributes.key?(:'is_locked')
        self.is_locked = attributes[:'is_locked']
      end

      if attributes.key?(:'flag_count')
        self.flag_count = attributes[:'flag_count']
      end

      if attributes.key?(:'display_label')
        self.display_label = attributes[:'display_label']
      end

      if attributes.key?(:'badges')
        if (value = attributes[:'badges']).is_a?(Array)
          self.badges = value
        end
      end

      if attributes.key?(:'verified')
        self.verified = attributes[:'verified']
      else
        self.verified = nil
      end

      if attributes.key?(:'feedback_ids')
        if (value = attributes[:'feedback_ids']).is_a?(Array)
          self.feedback_ids = value
        end
      end

      if attributes.key?(:'is_deleted')
        self.is_deleted = attributes[:'is_deleted']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @_id.nil?
        invalid_properties.push('invalid value for "_id", _id cannot be nil.')
      end

      if @tenant_id.nil?
        invalid_properties.push('invalid value for "tenant_id", tenant_id cannot be nil.')
      end

      if @url_id.nil?
        invalid_properties.push('invalid value for "url_id", url_id cannot be nil.')
      end

      if @url.nil?
        invalid_properties.push('invalid value for "url", url cannot be nil.')
      end

      if @commenter_name.nil?
        invalid_properties.push('invalid value for "commenter_name", commenter_name cannot be nil.')
      end

      if @comment_html.nil?
        invalid_properties.push('invalid value for "comment_html", comment_html cannot be nil.')
      end

      if @approved.nil?
        invalid_properties.push('invalid value for "approved", approved cannot be nil.')
      end

      if @verified.nil?
        invalid_properties.push('invalid value for "verified", verified cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @_id.nil?
      return false if @tenant_id.nil?
      return false if @url_id.nil?
      return false if @url.nil?
      return false if @commenter_name.nil?
      return false if @comment_html.nil?
      return false if @approved.nil?
      return false if @verified.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] _id Value to be assigned
    def _id=(_id)
      if _id.nil?
        fail ArgumentError, '_id cannot be nil'
      end

      @_id = _id
    end

    # Custom attribute writer method with validation
    # @param [Object] tenant_id Value to be assigned
    def tenant_id=(tenant_id)
      if tenant_id.nil?
        fail ArgumentError, 'tenant_id cannot be nil'
      end

      @tenant_id = tenant_id
    end

    # Custom attribute writer method with validation
    # @param [Object] url_id Value to be assigned
    def url_id=(url_id)
      if url_id.nil?
        fail ArgumentError, 'url_id cannot be nil'
      end

      @url_id = url_id
    end

    # Custom attribute writer method with validation
    # @param [Object] url Value to be assigned
    def url=(url)
      if url.nil?
        fail ArgumentError, 'url cannot be nil'
      end

      @url = url
    end

    # Custom attribute writer method with validation
    # @param [Object] commenter_name Value to be assigned
    def commenter_name=(commenter_name)
      if commenter_name.nil?
        fail ArgumentError, 'commenter_name cannot be nil'
      end

      @commenter_name = commenter_name
    end

    # Custom attribute writer method with validation
    # @param [Object] comment_html Value to be assigned
    def comment_html=(comment_html)
      if comment_html.nil?
        fail ArgumentError, 'comment_html cannot be nil'
      end

      @comment_html = comment_html
    end

    # Custom attribute writer method with validation
    # @param [Object] approved Value to be assigned
    def approved=(approved)
      if approved.nil?
        fail ArgumentError, 'approved cannot be nil'
      end

      @approved = approved
    end

    # Custom attribute writer method with validation
    # @param [Object] verified Value to be assigned
    def verified=(verified)
      if verified.nil?
        fail ArgumentError, 'verified cannot be nil'
      end

      @verified = verified
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          is_local_deleted == o.is_local_deleted &&
          reply_count == o.reply_count &&
          feedback_results == o.feedback_results &&
          is_voted_up == o.is_voted_up &&
          is_voted_down == o.is_voted_down &&
          my_vote_id == o.my_vote_id &&
          _id == o._id &&
          tenant_id == o.tenant_id &&
          url_id == o.url_id &&
          url == o.url &&
          page_title == o.page_title &&
          user_id == o.user_id &&
          anon_user_id == o.anon_user_id &&
          commenter_name == o.commenter_name &&
          commenter_link == o.commenter_link &&
          comment_html == o.comment_html &&
          parent_id == o.parent_id &&
          date == o.date &&
          local_date_string == o.local_date_string &&
          votes == o.votes &&
          votes_up == o.votes_up &&
          votes_down == o.votes_down &&
          expire_at == o.expire_at &&
          reviewed == o.reviewed &&
          avatar_src == o.avatar_src &&
          is_spam == o.is_spam &&
          perm_not_spam == o.perm_not_spam &&
          has_links == o.has_links &&
          has_code == o.has_code &&
          approved == o.approved &&
          locale == o.locale &&
          is_banned_user == o.is_banned_user &&
          is_by_admin == o.is_by_admin &&
          is_by_moderator == o.is_by_moderator &&
          is_pinned == o.is_pinned &&
          is_locked == o.is_locked &&
          flag_count == o.flag_count &&
          display_label == o.display_label &&
          badges == o.badges &&
          verified == o.verified &&
          feedback_ids == o.feedback_ids &&
          is_deleted == o.is_deleted
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [is_local_deleted, reply_count, feedback_results, is_voted_up, is_voted_down, my_vote_id, _id, tenant_id, url_id, url, page_title, user_id, anon_user_id, commenter_name, commenter_link, comment_html, parent_id, date, local_date_string, votes, votes_up, votes_down, expire_at, reviewed, avatar_src, is_spam, perm_not_spam, has_links, has_code, approved, locale, is_banned_user, is_by_admin, is_by_moderator, is_pinned, is_locked, flag_count, display_label, badges, verified, feedback_ids, is_deleted].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
