=begin
#fastcomments

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.19.0-SNAPSHOT

=end

require 'date'
require 'time'

module FastCommentsClient
  class QuestionConfig < ApiModelBase
    attr_accessor :_id

    attr_accessor :tenant_id

    attr_accessor :name

    attr_accessor :question

    attr_accessor :summary_label

    attr_accessor :help_text

    attr_accessor :created_at

    attr_accessor :created_by

    attr_accessor :used_count

    attr_accessor :last_used

    attr_accessor :type

    attr_accessor :num_stars

    attr_accessor :min

    attr_accessor :max

    attr_accessor :default_value

    attr_accessor :label_negative

    attr_accessor :label_positive

    attr_accessor :custom_options

    attr_accessor :sub_question_ids

    attr_accessor :always_show_sub_questions

    attr_accessor :reporting_order

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'_id' => :'_id',
        :'tenant_id' => :'tenantId',
        :'name' => :'name',
        :'question' => :'question',
        :'summary_label' => :'summaryLabel',
        :'help_text' => :'helpText',
        :'created_at' => :'createdAt',
        :'created_by' => :'createdBy',
        :'used_count' => :'usedCount',
        :'last_used' => :'lastUsed',
        :'type' => :'type',
        :'num_stars' => :'numStars',
        :'min' => :'min',
        :'max' => :'max',
        :'default_value' => :'defaultValue',
        :'label_negative' => :'labelNegative',
        :'label_positive' => :'labelPositive',
        :'custom_options' => :'customOptions',
        :'sub_question_ids' => :'subQuestionIds',
        :'always_show_sub_questions' => :'alwaysShowSubQuestions',
        :'reporting_order' => :'reportingOrder'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'_id' => :'String',
        :'tenant_id' => :'String',
        :'name' => :'String',
        :'question' => :'String',
        :'summary_label' => :'String',
        :'help_text' => :'String',
        :'created_at' => :'Time',
        :'created_by' => :'String',
        :'used_count' => :'Float',
        :'last_used' => :'Time',
        :'type' => :'String',
        :'num_stars' => :'Float',
        :'min' => :'Float',
        :'max' => :'Float',
        :'default_value' => :'Float',
        :'label_negative' => :'String',
        :'label_positive' => :'String',
        :'custom_options' => :'Array<QuestionConfigCustomOptionsInner>',
        :'sub_question_ids' => :'Array<String>',
        :'always_show_sub_questions' => :'Boolean',
        :'reporting_order' => :'Float'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `FastCommentsClient::QuestionConfig` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `FastCommentsClient::QuestionConfig`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'_id')
        self._id = attributes[:'_id']
      else
        self._id = nil
      end

      if attributes.key?(:'tenant_id')
        self.tenant_id = attributes[:'tenant_id']
      else
        self.tenant_id = nil
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      else
        self.name = nil
      end

      if attributes.key?(:'question')
        self.question = attributes[:'question']
      else
        self.question = nil
      end

      if attributes.key?(:'summary_label')
        self.summary_label = attributes[:'summary_label']
      end

      if attributes.key?(:'help_text')
        self.help_text = attributes[:'help_text']
      else
        self.help_text = nil
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      else
        self.created_at = nil
      end

      if attributes.key?(:'created_by')
        self.created_by = attributes[:'created_by']
      else
        self.created_by = nil
      end

      if attributes.key?(:'used_count')
        self.used_count = attributes[:'used_count']
      else
        self.used_count = nil
      end

      if attributes.key?(:'last_used')
        self.last_used = attributes[:'last_used']
      else
        self.last_used = nil
      end

      if attributes.key?(:'type')
        self.type = attributes[:'type']
      else
        self.type = nil
      end

      if attributes.key?(:'num_stars')
        self.num_stars = attributes[:'num_stars']
      else
        self.num_stars = nil
      end

      if attributes.key?(:'min')
        self.min = attributes[:'min']
      else
        self.min = nil
      end

      if attributes.key?(:'max')
        self.max = attributes[:'max']
      else
        self.max = nil
      end

      if attributes.key?(:'default_value')
        self.default_value = attributes[:'default_value']
      else
        self.default_value = nil
      end

      if attributes.key?(:'label_negative')
        self.label_negative = attributes[:'label_negative']
      else
        self.label_negative = nil
      end

      if attributes.key?(:'label_positive')
        self.label_positive = attributes[:'label_positive']
      else
        self.label_positive = nil
      end

      if attributes.key?(:'custom_options')
        if (value = attributes[:'custom_options']).is_a?(Array)
          self.custom_options = value
        end
      else
        self.custom_options = nil
      end

      if attributes.key?(:'sub_question_ids')
        if (value = attributes[:'sub_question_ids']).is_a?(Array)
          self.sub_question_ids = value
        end
      else
        self.sub_question_ids = nil
      end

      if attributes.key?(:'always_show_sub_questions')
        self.always_show_sub_questions = attributes[:'always_show_sub_questions']
      else
        self.always_show_sub_questions = nil
      end

      if attributes.key?(:'reporting_order')
        self.reporting_order = attributes[:'reporting_order']
      else
        self.reporting_order = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @_id.nil?
        invalid_properties.push('invalid value for "_id", _id cannot be nil.')
      end

      if @tenant_id.nil?
        invalid_properties.push('invalid value for "tenant_id", tenant_id cannot be nil.')
      end

      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      if @question.nil?
        invalid_properties.push('invalid value for "question", question cannot be nil.')
      end

      if @help_text.nil?
        invalid_properties.push('invalid value for "help_text", help_text cannot be nil.')
      end

      if @created_at.nil?
        invalid_properties.push('invalid value for "created_at", created_at cannot be nil.')
      end

      if @created_by.nil?
        invalid_properties.push('invalid value for "created_by", created_by cannot be nil.')
      end

      if @used_count.nil?
        invalid_properties.push('invalid value for "used_count", used_count cannot be nil.')
      end

      if @last_used.nil?
        invalid_properties.push('invalid value for "last_used", last_used cannot be nil.')
      end

      if @type.nil?
        invalid_properties.push('invalid value for "type", type cannot be nil.')
      end

      if @num_stars.nil?
        invalid_properties.push('invalid value for "num_stars", num_stars cannot be nil.')
      end

      if @min.nil?
        invalid_properties.push('invalid value for "min", min cannot be nil.')
      end

      if @max.nil?
        invalid_properties.push('invalid value for "max", max cannot be nil.')
      end

      if @default_value.nil?
        invalid_properties.push('invalid value for "default_value", default_value cannot be nil.')
      end

      if @label_negative.nil?
        invalid_properties.push('invalid value for "label_negative", label_negative cannot be nil.')
      end

      if @label_positive.nil?
        invalid_properties.push('invalid value for "label_positive", label_positive cannot be nil.')
      end

      if @custom_options.nil?
        invalid_properties.push('invalid value for "custom_options", custom_options cannot be nil.')
      end

      if @sub_question_ids.nil?
        invalid_properties.push('invalid value for "sub_question_ids", sub_question_ids cannot be nil.')
      end

      if @always_show_sub_questions.nil?
        invalid_properties.push('invalid value for "always_show_sub_questions", always_show_sub_questions cannot be nil.')
      end

      if @reporting_order.nil?
        invalid_properties.push('invalid value for "reporting_order", reporting_order cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @_id.nil?
      return false if @tenant_id.nil?
      return false if @name.nil?
      return false if @question.nil?
      return false if @help_text.nil?
      return false if @created_at.nil?
      return false if @created_by.nil?
      return false if @used_count.nil?
      return false if @last_used.nil?
      return false if @type.nil?
      return false if @num_stars.nil?
      return false if @min.nil?
      return false if @max.nil?
      return false if @default_value.nil?
      return false if @label_negative.nil?
      return false if @label_positive.nil?
      return false if @custom_options.nil?
      return false if @sub_question_ids.nil?
      return false if @always_show_sub_questions.nil?
      return false if @reporting_order.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] _id Value to be assigned
    def _id=(_id)
      if _id.nil?
        fail ArgumentError, '_id cannot be nil'
      end

      @_id = _id
    end

    # Custom attribute writer method with validation
    # @param [Object] tenant_id Value to be assigned
    def tenant_id=(tenant_id)
      if tenant_id.nil?
        fail ArgumentError, 'tenant_id cannot be nil'
      end

      @tenant_id = tenant_id
    end

    # Custom attribute writer method with validation
    # @param [Object] name Value to be assigned
    def name=(name)
      if name.nil?
        fail ArgumentError, 'name cannot be nil'
      end

      @name = name
    end

    # Custom attribute writer method with validation
    # @param [Object] question Value to be assigned
    def question=(question)
      if question.nil?
        fail ArgumentError, 'question cannot be nil'
      end

      @question = question
    end

    # Custom attribute writer method with validation
    # @param [Object] help_text Value to be assigned
    def help_text=(help_text)
      if help_text.nil?
        fail ArgumentError, 'help_text cannot be nil'
      end

      @help_text = help_text
    end

    # Custom attribute writer method with validation
    # @param [Object] created_at Value to be assigned
    def created_at=(created_at)
      if created_at.nil?
        fail ArgumentError, 'created_at cannot be nil'
      end

      @created_at = created_at
    end

    # Custom attribute writer method with validation
    # @param [Object] created_by Value to be assigned
    def created_by=(created_by)
      if created_by.nil?
        fail ArgumentError, 'created_by cannot be nil'
      end

      @created_by = created_by
    end

    # Custom attribute writer method with validation
    # @param [Object] used_count Value to be assigned
    def used_count=(used_count)
      if used_count.nil?
        fail ArgumentError, 'used_count cannot be nil'
      end

      @used_count = used_count
    end

    # Custom attribute writer method with validation
    # @param [Object] last_used Value to be assigned
    def last_used=(last_used)
      if last_used.nil?
        fail ArgumentError, 'last_used cannot be nil'
      end

      @last_used = last_used
    end

    # Custom attribute writer method with validation
    # @param [Object] type Value to be assigned
    def type=(type)
      if type.nil?
        fail ArgumentError, 'type cannot be nil'
      end

      @type = type
    end

    # Custom attribute writer method with validation
    # @param [Object] num_stars Value to be assigned
    def num_stars=(num_stars)
      if num_stars.nil?
        fail ArgumentError, 'num_stars cannot be nil'
      end

      @num_stars = num_stars
    end

    # Custom attribute writer method with validation
    # @param [Object] min Value to be assigned
    def min=(min)
      if min.nil?
        fail ArgumentError, 'min cannot be nil'
      end

      @min = min
    end

    # Custom attribute writer method with validation
    # @param [Object] max Value to be assigned
    def max=(max)
      if max.nil?
        fail ArgumentError, 'max cannot be nil'
      end

      @max = max
    end

    # Custom attribute writer method with validation
    # @param [Object] default_value Value to be assigned
    def default_value=(default_value)
      if default_value.nil?
        fail ArgumentError, 'default_value cannot be nil'
      end

      @default_value = default_value
    end

    # Custom attribute writer method with validation
    # @param [Object] label_negative Value to be assigned
    def label_negative=(label_negative)
      if label_negative.nil?
        fail ArgumentError, 'label_negative cannot be nil'
      end

      @label_negative = label_negative
    end

    # Custom attribute writer method with validation
    # @param [Object] label_positive Value to be assigned
    def label_positive=(label_positive)
      if label_positive.nil?
        fail ArgumentError, 'label_positive cannot be nil'
      end

      @label_positive = label_positive
    end

    # Custom attribute writer method with validation
    # @param [Object] custom_options Value to be assigned
    def custom_options=(custom_options)
      if custom_options.nil?
        fail ArgumentError, 'custom_options cannot be nil'
      end

      @custom_options = custom_options
    end

    # Custom attribute writer method with validation
    # @param [Object] sub_question_ids Value to be assigned
    def sub_question_ids=(sub_question_ids)
      if sub_question_ids.nil?
        fail ArgumentError, 'sub_question_ids cannot be nil'
      end

      @sub_question_ids = sub_question_ids
    end

    # Custom attribute writer method with validation
    # @param [Object] always_show_sub_questions Value to be assigned
    def always_show_sub_questions=(always_show_sub_questions)
      if always_show_sub_questions.nil?
        fail ArgumentError, 'always_show_sub_questions cannot be nil'
      end

      @always_show_sub_questions = always_show_sub_questions
    end

    # Custom attribute writer method with validation
    # @param [Object] reporting_order Value to be assigned
    def reporting_order=(reporting_order)
      if reporting_order.nil?
        fail ArgumentError, 'reporting_order cannot be nil'
      end

      @reporting_order = reporting_order
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          _id == o._id &&
          tenant_id == o.tenant_id &&
          name == o.name &&
          question == o.question &&
          summary_label == o.summary_label &&
          help_text == o.help_text &&
          created_at == o.created_at &&
          created_by == o.created_by &&
          used_count == o.used_count &&
          last_used == o.last_used &&
          type == o.type &&
          num_stars == o.num_stars &&
          min == o.min &&
          max == o.max &&
          default_value == o.default_value &&
          label_negative == o.label_negative &&
          label_positive == o.label_positive &&
          custom_options == o.custom_options &&
          sub_question_ids == o.sub_question_ids &&
          always_show_sub_questions == o.always_show_sub_questions &&
          reporting_order == o.reporting_order
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [_id, tenant_id, name, question, summary_label, help_text, created_at, created_by, used_count, last_used, type, num_stars, min, max, default_value, label_negative, label_positive, custom_options, sub_question_ids, always_show_sub_questions, reporting_order].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
