=begin
#fastcomments

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.19.0-SNAPSHOT

=end

require 'date'
require 'time'

module FastCommentsClient
  class RepeatCommentCheckIgnoredReason
    N0 = 0.freeze
    N1 = 1.freeze
    N2 = 2.freeze
    N3 = 3.freeze
    N4 = 4.freeze
    N5 = 5.freeze
    N6 = 6.freeze

    def self.all_vars
      @all_vars ||= [N0, N1, N2, N3, N4, N5, N6].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if RepeatCommentCheckIgnoredReason.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #RepeatCommentCheckIgnoredReason"
    end
  end
end
