=begin
#fastcomments

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.19.0-SNAPSHOT

=end

require 'date'
require 'time'

module FastCommentsClient
  class UpdateTenantBody < ApiModelBase
    attr_accessor :name

    attr_accessor :email

    attr_accessor :sign_up_date

    attr_accessor :package_id

    attr_accessor :payment_frequency

    attr_accessor :billing_info_valid

    attr_accessor :billing_handled_externally

    attr_accessor :created_by

    attr_accessor :is_setup

    attr_accessor :domain_configuration

    attr_accessor :billing_info

    attr_accessor :stripe_customer_id

    attr_accessor :stripe_subscription_id

    attr_accessor :stripe_plan_id

    attr_accessor :enable_profanity_filter

    attr_accessor :enable_spam_filter

    attr_accessor :remove_unverified_comments

    attr_accessor :unverified_comments_tt_lms

    attr_accessor :comments_require_approval

    attr_accessor :auto_approve_comment_on_verification

    attr_accessor :send_profane_to_spam

    attr_accessor :de_anon_ip_addr

    # Construct a type with a set of properties K of type T
    attr_accessor :meta

    attr_accessor :managed_by_tenant_id

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'name' => :'name',
        :'email' => :'email',
        :'sign_up_date' => :'signUpDate',
        :'package_id' => :'packageId',
        :'payment_frequency' => :'paymentFrequency',
        :'billing_info_valid' => :'billingInfoValid',
        :'billing_handled_externally' => :'billingHandledExternally',
        :'created_by' => :'createdBy',
        :'is_setup' => :'isSetup',
        :'domain_configuration' => :'domainConfiguration',
        :'billing_info' => :'billingInfo',
        :'stripe_customer_id' => :'stripeCustomerId',
        :'stripe_subscription_id' => :'stripeSubscriptionId',
        :'stripe_plan_id' => :'stripePlanId',
        :'enable_profanity_filter' => :'enableProfanityFilter',
        :'enable_spam_filter' => :'enableSpamFilter',
        :'remove_unverified_comments' => :'removeUnverifiedComments',
        :'unverified_comments_tt_lms' => :'unverifiedCommentsTTLms',
        :'comments_require_approval' => :'commentsRequireApproval',
        :'auto_approve_comment_on_verification' => :'autoApproveCommentOnVerification',
        :'send_profane_to_spam' => :'sendProfaneToSpam',
        :'de_anon_ip_addr' => :'deAnonIpAddr',
        :'meta' => :'meta',
        :'managed_by_tenant_id' => :'managedByTenantId'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'name' => :'String',
        :'email' => :'String',
        :'sign_up_date' => :'Float',
        :'package_id' => :'String',
        :'payment_frequency' => :'Float',
        :'billing_info_valid' => :'Boolean',
        :'billing_handled_externally' => :'Boolean',
        :'created_by' => :'String',
        :'is_setup' => :'Boolean',
        :'domain_configuration' => :'Array<APIDomainConfiguration>',
        :'billing_info' => :'BillingInfo',
        :'stripe_customer_id' => :'String',
        :'stripe_subscription_id' => :'String',
        :'stripe_plan_id' => :'String',
        :'enable_profanity_filter' => :'Boolean',
        :'enable_spam_filter' => :'Boolean',
        :'remove_unverified_comments' => :'Boolean',
        :'unverified_comments_tt_lms' => :'Float',
        :'comments_require_approval' => :'Boolean',
        :'auto_approve_comment_on_verification' => :'Boolean',
        :'send_profane_to_spam' => :'Boolean',
        :'de_anon_ip_addr' => :'Float',
        :'meta' => :'Hash<String, String>',
        :'managed_by_tenant_id' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `FastCommentsClient::UpdateTenantBody` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `FastCommentsClient::UpdateTenantBody`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'email')
        self.email = attributes[:'email']
      end

      if attributes.key?(:'sign_up_date')
        self.sign_up_date = attributes[:'sign_up_date']
      end

      if attributes.key?(:'package_id')
        self.package_id = attributes[:'package_id']
      end

      if attributes.key?(:'payment_frequency')
        self.payment_frequency = attributes[:'payment_frequency']
      end

      if attributes.key?(:'billing_info_valid')
        self.billing_info_valid = attributes[:'billing_info_valid']
      end

      if attributes.key?(:'billing_handled_externally')
        self.billing_handled_externally = attributes[:'billing_handled_externally']
      end

      if attributes.key?(:'created_by')
        self.created_by = attributes[:'created_by']
      end

      if attributes.key?(:'is_setup')
        self.is_setup = attributes[:'is_setup']
      end

      if attributes.key?(:'domain_configuration')
        if (value = attributes[:'domain_configuration']).is_a?(Array)
          self.domain_configuration = value
        end
      end

      if attributes.key?(:'billing_info')
        self.billing_info = attributes[:'billing_info']
      end

      if attributes.key?(:'stripe_customer_id')
        self.stripe_customer_id = attributes[:'stripe_customer_id']
      end

      if attributes.key?(:'stripe_subscription_id')
        self.stripe_subscription_id = attributes[:'stripe_subscription_id']
      end

      if attributes.key?(:'stripe_plan_id')
        self.stripe_plan_id = attributes[:'stripe_plan_id']
      end

      if attributes.key?(:'enable_profanity_filter')
        self.enable_profanity_filter = attributes[:'enable_profanity_filter']
      end

      if attributes.key?(:'enable_spam_filter')
        self.enable_spam_filter = attributes[:'enable_spam_filter']
      end

      if attributes.key?(:'remove_unverified_comments')
        self.remove_unverified_comments = attributes[:'remove_unverified_comments']
      end

      if attributes.key?(:'unverified_comments_tt_lms')
        self.unverified_comments_tt_lms = attributes[:'unverified_comments_tt_lms']
      end

      if attributes.key?(:'comments_require_approval')
        self.comments_require_approval = attributes[:'comments_require_approval']
      end

      if attributes.key?(:'auto_approve_comment_on_verification')
        self.auto_approve_comment_on_verification = attributes[:'auto_approve_comment_on_verification']
      end

      if attributes.key?(:'send_profane_to_spam')
        self.send_profane_to_spam = attributes[:'send_profane_to_spam']
      end

      if attributes.key?(:'de_anon_ip_addr')
        self.de_anon_ip_addr = attributes[:'de_anon_ip_addr']
      end

      if attributes.key?(:'meta')
        if (value = attributes[:'meta']).is_a?(Hash)
          self.meta = value
        end
      end

      if attributes.key?(:'managed_by_tenant_id')
        self.managed_by_tenant_id = attributes[:'managed_by_tenant_id']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          name == o.name &&
          email == o.email &&
          sign_up_date == o.sign_up_date &&
          package_id == o.package_id &&
          payment_frequency == o.payment_frequency &&
          billing_info_valid == o.billing_info_valid &&
          billing_handled_externally == o.billing_handled_externally &&
          created_by == o.created_by &&
          is_setup == o.is_setup &&
          domain_configuration == o.domain_configuration &&
          billing_info == o.billing_info &&
          stripe_customer_id == o.stripe_customer_id &&
          stripe_subscription_id == o.stripe_subscription_id &&
          stripe_plan_id == o.stripe_plan_id &&
          enable_profanity_filter == o.enable_profanity_filter &&
          enable_spam_filter == o.enable_spam_filter &&
          remove_unverified_comments == o.remove_unverified_comments &&
          unverified_comments_tt_lms == o.unverified_comments_tt_lms &&
          comments_require_approval == o.comments_require_approval &&
          auto_approve_comment_on_verification == o.auto_approve_comment_on_verification &&
          send_profane_to_spam == o.send_profane_to_spam &&
          de_anon_ip_addr == o.de_anon_ip_addr &&
          meta == o.meta &&
          managed_by_tenant_id == o.managed_by_tenant_id
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [name, email, sign_up_date, package_id, payment_frequency, billing_info_valid, billing_handled_externally, created_by, is_setup, domain_configuration, billing_info, stripe_customer_id, stripe_subscription_id, stripe_plan_id, enable_profanity_filter, enable_spam_filter, remove_unverified_comments, unverified_comments_tt_lms, comments_require_approval, auto_approve_comment_on_verification, send_profane_to_spam, de_anon_ip_addr, meta, managed_by_tenant_id].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
