=begin
#fastcomments

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'date'
require 'time'

module FastCommentsClient
  class UserNotification
    attr_accessor :_id

    attr_accessor :tenant_id

    attr_accessor :user_id

    attr_accessor :anon_user_id

    attr_accessor :url_id

    attr_accessor :url

    attr_accessor :page_title

    attr_accessor :related_object_type

    attr_accessor :related_object_id

    attr_accessor :viewed

    attr_accessor :is_unread_message

    attr_accessor :sent

    attr_accessor :created_at

    attr_accessor :type

    attr_accessor :from_comment_id

    attr_accessor :from_vote_id

    attr_accessor :from_user_name

    attr_accessor :from_user_id

    attr_accessor :from_user_avatar_src

    attr_accessor :opted_out

    attr_accessor :count

    attr_accessor :related_ids

    attr_accessor :from_user_ids

    attr_accessor :from_user_names

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'_id' => :'_id',
        :'tenant_id' => :'tenantId',
        :'user_id' => :'userId',
        :'anon_user_id' => :'anonUserId',
        :'url_id' => :'urlId',
        :'url' => :'url',
        :'page_title' => :'pageTitle',
        :'related_object_type' => :'relatedObjectType',
        :'related_object_id' => :'relatedObjectId',
        :'viewed' => :'viewed',
        :'is_unread_message' => :'isUnreadMessage',
        :'sent' => :'sent',
        :'created_at' => :'createdAt',
        :'type' => :'type',
        :'from_comment_id' => :'fromCommentId',
        :'from_vote_id' => :'fromVoteId',
        :'from_user_name' => :'fromUserName',
        :'from_user_id' => :'fromUserId',
        :'from_user_avatar_src' => :'fromUserAvatarSrc',
        :'opted_out' => :'optedOut',
        :'count' => :'count',
        :'related_ids' => :'relatedIds',
        :'from_user_ids' => :'fromUserIds',
        :'from_user_names' => :'fromUserNames'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'_id' => :'String',
        :'tenant_id' => :'String',
        :'user_id' => :'String',
        :'anon_user_id' => :'String',
        :'url_id' => :'String',
        :'url' => :'String',
        :'page_title' => :'String',
        :'related_object_type' => :'NotificationObjectType',
        :'related_object_id' => :'String',
        :'viewed' => :'Boolean',
        :'is_unread_message' => :'Boolean',
        :'sent' => :'Boolean',
        :'created_at' => :'Time',
        :'type' => :'NotificationType',
        :'from_comment_id' => :'String',
        :'from_vote_id' => :'String',
        :'from_user_name' => :'String',
        :'from_user_id' => :'String',
        :'from_user_avatar_src' => :'String',
        :'opted_out' => :'Boolean',
        :'count' => :'Integer',
        :'related_ids' => :'Array<String>',
        :'from_user_ids' => :'Array<String>',
        :'from_user_names' => :'Array<String>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'user_id',
        :'anon_user_id',
        :'page_title',
        :'from_comment_id',
        :'from_vote_id',
        :'from_user_name',
        :'from_user_id',
        :'from_user_avatar_src',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `FastCommentsClient::UserNotification` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `FastCommentsClient::UserNotification`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'_id')
        self._id = attributes[:'_id']
      else
        self._id = nil
      end

      if attributes.key?(:'tenant_id')
        self.tenant_id = attributes[:'tenant_id']
      else
        self.tenant_id = nil
      end

      if attributes.key?(:'user_id')
        self.user_id = attributes[:'user_id']
      end

      if attributes.key?(:'anon_user_id')
        self.anon_user_id = attributes[:'anon_user_id']
      end

      if attributes.key?(:'url_id')
        self.url_id = attributes[:'url_id']
      else
        self.url_id = nil
      end

      if attributes.key?(:'url')
        self.url = attributes[:'url']
      else
        self.url = nil
      end

      if attributes.key?(:'page_title')
        self.page_title = attributes[:'page_title']
      end

      if attributes.key?(:'related_object_type')
        self.related_object_type = attributes[:'related_object_type']
      else
        self.related_object_type = nil
      end

      if attributes.key?(:'related_object_id')
        self.related_object_id = attributes[:'related_object_id']
      else
        self.related_object_id = nil
      end

      if attributes.key?(:'viewed')
        self.viewed = attributes[:'viewed']
      else
        self.viewed = nil
      end

      if attributes.key?(:'is_unread_message')
        self.is_unread_message = attributes[:'is_unread_message']
      else
        self.is_unread_message = nil
      end

      if attributes.key?(:'sent')
        self.sent = attributes[:'sent']
      else
        self.sent = nil
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      else
        self.created_at = nil
      end

      if attributes.key?(:'type')
        self.type = attributes[:'type']
      else
        self.type = nil
      end

      if attributes.key?(:'from_comment_id')
        self.from_comment_id = attributes[:'from_comment_id']
      end

      if attributes.key?(:'from_vote_id')
        self.from_vote_id = attributes[:'from_vote_id']
      end

      if attributes.key?(:'from_user_name')
        self.from_user_name = attributes[:'from_user_name']
      end

      if attributes.key?(:'from_user_id')
        self.from_user_id = attributes[:'from_user_id']
      end

      if attributes.key?(:'from_user_avatar_src')
        self.from_user_avatar_src = attributes[:'from_user_avatar_src']
      end

      if attributes.key?(:'opted_out')
        self.opted_out = attributes[:'opted_out']
      else
        self.opted_out = nil
      end

      if attributes.key?(:'count')
        self.count = attributes[:'count']
      end

      if attributes.key?(:'related_ids')
        if (value = attributes[:'related_ids']).is_a?(Array)
          self.related_ids = value
        end
      end

      if attributes.key?(:'from_user_ids')
        if (value = attributes[:'from_user_ids']).is_a?(Array)
          self.from_user_ids = value
        end
      end

      if attributes.key?(:'from_user_names')
        if (value = attributes[:'from_user_names']).is_a?(Array)
          self.from_user_names = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @_id.nil?
        invalid_properties.push('invalid value for "_id", _id cannot be nil.')
      end

      if @tenant_id.nil?
        invalid_properties.push('invalid value for "tenant_id", tenant_id cannot be nil.')
      end

      if @url_id.nil?
        invalid_properties.push('invalid value for "url_id", url_id cannot be nil.')
      end

      if @url.nil?
        invalid_properties.push('invalid value for "url", url cannot be nil.')
      end

      if @related_object_type.nil?
        invalid_properties.push('invalid value for "related_object_type", related_object_type cannot be nil.')
      end

      if @related_object_id.nil?
        invalid_properties.push('invalid value for "related_object_id", related_object_id cannot be nil.')
      end

      if @viewed.nil?
        invalid_properties.push('invalid value for "viewed", viewed cannot be nil.')
      end

      if @is_unread_message.nil?
        invalid_properties.push('invalid value for "is_unread_message", is_unread_message cannot be nil.')
      end

      if @sent.nil?
        invalid_properties.push('invalid value for "sent", sent cannot be nil.')
      end

      if @created_at.nil?
        invalid_properties.push('invalid value for "created_at", created_at cannot be nil.')
      end

      if @type.nil?
        invalid_properties.push('invalid value for "type", type cannot be nil.')
      end

      if @opted_out.nil?
        invalid_properties.push('invalid value for "opted_out", opted_out cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @_id.nil?
      return false if @tenant_id.nil?
      return false if @url_id.nil?
      return false if @url.nil?
      return false if @related_object_type.nil?
      return false if @related_object_id.nil?
      return false if @viewed.nil?
      return false if @is_unread_message.nil?
      return false if @sent.nil?
      return false if @created_at.nil?
      return false if @type.nil?
      return false if @opted_out.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] _id Value to be assigned
    def _id=(_id)
      if _id.nil?
        fail ArgumentError, '_id cannot be nil'
      end

      @_id = _id
    end

    # Custom attribute writer method with validation
    # @param [Object] tenant_id Value to be assigned
    def tenant_id=(tenant_id)
      if tenant_id.nil?
        fail ArgumentError, 'tenant_id cannot be nil'
      end

      @tenant_id = tenant_id
    end

    # Custom attribute writer method with validation
    # @param [Object] url_id Value to be assigned
    def url_id=(url_id)
      if url_id.nil?
        fail ArgumentError, 'url_id cannot be nil'
      end

      @url_id = url_id
    end

    # Custom attribute writer method with validation
    # @param [Object] url Value to be assigned
    def url=(url)
      if url.nil?
        fail ArgumentError, 'url cannot be nil'
      end

      @url = url
    end

    # Custom attribute writer method with validation
    # @param [Object] related_object_type Value to be assigned
    def related_object_type=(related_object_type)
      if related_object_type.nil?
        fail ArgumentError, 'related_object_type cannot be nil'
      end

      @related_object_type = related_object_type
    end

    # Custom attribute writer method with validation
    # @param [Object] related_object_id Value to be assigned
    def related_object_id=(related_object_id)
      if related_object_id.nil?
        fail ArgumentError, 'related_object_id cannot be nil'
      end

      @related_object_id = related_object_id
    end

    # Custom attribute writer method with validation
    # @param [Object] viewed Value to be assigned
    def viewed=(viewed)
      if viewed.nil?
        fail ArgumentError, 'viewed cannot be nil'
      end

      @viewed = viewed
    end

    # Custom attribute writer method with validation
    # @param [Object] is_unread_message Value to be assigned
    def is_unread_message=(is_unread_message)
      if is_unread_message.nil?
        fail ArgumentError, 'is_unread_message cannot be nil'
      end

      @is_unread_message = is_unread_message
    end

    # Custom attribute writer method with validation
    # @param [Object] sent Value to be assigned
    def sent=(sent)
      if sent.nil?
        fail ArgumentError, 'sent cannot be nil'
      end

      @sent = sent
    end

    # Custom attribute writer method with validation
    # @param [Object] created_at Value to be assigned
    def created_at=(created_at)
      if created_at.nil?
        fail ArgumentError, 'created_at cannot be nil'
      end

      @created_at = created_at
    end

    # Custom attribute writer method with validation
    # @param [Object] type Value to be assigned
    def type=(type)
      if type.nil?
        fail ArgumentError, 'type cannot be nil'
      end

      @type = type
    end

    # Custom attribute writer method with validation
    # @param [Object] opted_out Value to be assigned
    def opted_out=(opted_out)
      if opted_out.nil?
        fail ArgumentError, 'opted_out cannot be nil'
      end

      @opted_out = opted_out
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          _id == o._id &&
          tenant_id == o.tenant_id &&
          user_id == o.user_id &&
          anon_user_id == o.anon_user_id &&
          url_id == o.url_id &&
          url == o.url &&
          page_title == o.page_title &&
          related_object_type == o.related_object_type &&
          related_object_id == o.related_object_id &&
          viewed == o.viewed &&
          is_unread_message == o.is_unread_message &&
          sent == o.sent &&
          created_at == o.created_at &&
          type == o.type &&
          from_comment_id == o.from_comment_id &&
          from_vote_id == o.from_vote_id &&
          from_user_name == o.from_user_name &&
          from_user_id == o.from_user_id &&
          from_user_avatar_src == o.from_user_avatar_src &&
          opted_out == o.opted_out &&
          count == o.count &&
          related_ids == o.related_ids &&
          from_user_ids == o.from_user_ids &&
          from_user_names == o.from_user_names
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [_id, tenant_id, user_id, anon_user_id, url_id, url, page_title, related_object_type, related_object_id, viewed, is_unread_message, sent, created_at, type, from_comment_id, from_vote_id, from_user_name, from_user_id, from_user_avatar_src, opted_out, count, related_ids, from_user_ids, from_user_names].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = FastCommentsClient.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
