=begin
#fastcomments

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.18.0-SNAPSHOT

=end

require 'date'
require 'time'

module FastCommentsClient
  class UserBadgeProgress < ApiModelBase
    attr_accessor :_id

    attr_accessor :tenant_id

    attr_accessor :user_id

    attr_accessor :first_comment_id

    attr_accessor :first_comment_date

    attr_accessor :auto_trust_factor

    attr_accessor :manual_trust_factor

    # Construct a type with a set of properties K of type T
    attr_accessor :progress

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'_id' => :'_id',
        :'tenant_id' => :'tenantId',
        :'user_id' => :'userId',
        :'first_comment_id' => :'firstCommentId',
        :'first_comment_date' => :'firstCommentDate',
        :'auto_trust_factor' => :'autoTrustFactor',
        :'manual_trust_factor' => :'manualTrustFactor',
        :'progress' => :'progress'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'_id' => :'String',
        :'tenant_id' => :'String',
        :'user_id' => :'String',
        :'first_comment_id' => :'String',
        :'first_comment_date' => :'Time',
        :'auto_trust_factor' => :'Float',
        :'manual_trust_factor' => :'Float',
        :'progress' => :'Hash<String, Float>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `FastCommentsClient::UserBadgeProgress` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `FastCommentsClient::UserBadgeProgress`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'_id')
        self._id = attributes[:'_id']
      else
        self._id = nil
      end

      if attributes.key?(:'tenant_id')
        self.tenant_id = attributes[:'tenant_id']
      else
        self.tenant_id = nil
      end

      if attributes.key?(:'user_id')
        self.user_id = attributes[:'user_id']
      else
        self.user_id = nil
      end

      if attributes.key?(:'first_comment_id')
        self.first_comment_id = attributes[:'first_comment_id']
      else
        self.first_comment_id = nil
      end

      if attributes.key?(:'first_comment_date')
        self.first_comment_date = attributes[:'first_comment_date']
      else
        self.first_comment_date = nil
      end

      if attributes.key?(:'auto_trust_factor')
        self.auto_trust_factor = attributes[:'auto_trust_factor']
      end

      if attributes.key?(:'manual_trust_factor')
        self.manual_trust_factor = attributes[:'manual_trust_factor']
      end

      if attributes.key?(:'progress')
        if (value = attributes[:'progress']).is_a?(Hash)
          self.progress = value
        end
      else
        self.progress = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @_id.nil?
        invalid_properties.push('invalid value for "_id", _id cannot be nil.')
      end

      if @tenant_id.nil?
        invalid_properties.push('invalid value for "tenant_id", tenant_id cannot be nil.')
      end

      if @user_id.nil?
        invalid_properties.push('invalid value for "user_id", user_id cannot be nil.')
      end

      if @first_comment_id.nil?
        invalid_properties.push('invalid value for "first_comment_id", first_comment_id cannot be nil.')
      end

      if @first_comment_date.nil?
        invalid_properties.push('invalid value for "first_comment_date", first_comment_date cannot be nil.')
      end

      if @progress.nil?
        invalid_properties.push('invalid value for "progress", progress cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @_id.nil?
      return false if @tenant_id.nil?
      return false if @user_id.nil?
      return false if @first_comment_id.nil?
      return false if @first_comment_date.nil?
      return false if @progress.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] _id Value to be assigned
    def _id=(_id)
      if _id.nil?
        fail ArgumentError, '_id cannot be nil'
      end

      @_id = _id
    end

    # Custom attribute writer method with validation
    # @param [Object] tenant_id Value to be assigned
    def tenant_id=(tenant_id)
      if tenant_id.nil?
        fail ArgumentError, 'tenant_id cannot be nil'
      end

      @tenant_id = tenant_id
    end

    # Custom attribute writer method with validation
    # @param [Object] user_id Value to be assigned
    def user_id=(user_id)
      if user_id.nil?
        fail ArgumentError, 'user_id cannot be nil'
      end

      @user_id = user_id
    end

    # Custom attribute writer method with validation
    # @param [Object] first_comment_id Value to be assigned
    def first_comment_id=(first_comment_id)
      if first_comment_id.nil?
        fail ArgumentError, 'first_comment_id cannot be nil'
      end

      @first_comment_id = first_comment_id
    end

    # Custom attribute writer method with validation
    # @param [Object] first_comment_date Value to be assigned
    def first_comment_date=(first_comment_date)
      if first_comment_date.nil?
        fail ArgumentError, 'first_comment_date cannot be nil'
      end

      @first_comment_date = first_comment_date
    end

    # Custom attribute writer method with validation
    # @param [Object] progress Value to be assigned
    def progress=(progress)
      if progress.nil?
        fail ArgumentError, 'progress cannot be nil'
      end

      @progress = progress
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          _id == o._id &&
          tenant_id == o.tenant_id &&
          user_id == o.user_id &&
          first_comment_id == o.first_comment_id &&
          first_comment_date == o.first_comment_date &&
          auto_trust_factor == o.auto_trust_factor &&
          manual_trust_factor == o.manual_trust_factor &&
          progress == o.progress
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [_id, tenant_id, user_id, first_comment_id, first_comment_date, auto_trust_factor, manual_trust_factor, progress].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
