=begin
#fastcomments

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.19.0-SNAPSHOT

=end

require 'date'
require 'time'

module FastCommentsClient
  class UserSessionInfo < ApiModelBase
    attr_accessor :id

    attr_accessor :authorized

    attr_accessor :avatar_src

    attr_accessor :badges

    attr_accessor :display_label

    attr_accessor :display_name

    attr_accessor :email

    attr_accessor :group_ids

    attr_accessor :has_blocked_users

    attr_accessor :is_anon_session

    attr_accessor :session_id

    attr_accessor :username

    attr_accessor :website_url

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'authorized' => :'authorized',
        :'avatar_src' => :'avatarSrc',
        :'badges' => :'badges',
        :'display_label' => :'displayLabel',
        :'display_name' => :'displayName',
        :'email' => :'email',
        :'group_ids' => :'groupIds',
        :'has_blocked_users' => :'hasBlockedUsers',
        :'is_anon_session' => :'isAnonSession',
        :'session_id' => :'sessionId',
        :'username' => :'username',
        :'website_url' => :'websiteUrl'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'authorized' => :'Boolean',
        :'avatar_src' => :'String',
        :'badges' => :'Array<CommentUserBadgeInfo>',
        :'display_label' => :'String',
        :'display_name' => :'String',
        :'email' => :'String',
        :'group_ids' => :'Array<String>',
        :'has_blocked_users' => :'Boolean',
        :'is_anon_session' => :'Boolean',
        :'session_id' => :'String',
        :'username' => :'String',
        :'website_url' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'avatar_src',
        :'email',
        :'session_id',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `FastCommentsClient::UserSessionInfo` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `FastCommentsClient::UserSessionInfo`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'authorized')
        self.authorized = attributes[:'authorized']
      end

      if attributes.key?(:'avatar_src')
        self.avatar_src = attributes[:'avatar_src']
      end

      if attributes.key?(:'badges')
        if (value = attributes[:'badges']).is_a?(Array)
          self.badges = value
        end
      end

      if attributes.key?(:'display_label')
        self.display_label = attributes[:'display_label']
      end

      if attributes.key?(:'display_name')
        self.display_name = attributes[:'display_name']
      end

      if attributes.key?(:'email')
        self.email = attributes[:'email']
      end

      if attributes.key?(:'group_ids')
        if (value = attributes[:'group_ids']).is_a?(Array)
          self.group_ids = value
        end
      end

      if attributes.key?(:'has_blocked_users')
        self.has_blocked_users = attributes[:'has_blocked_users']
      end

      if attributes.key?(:'is_anon_session')
        self.is_anon_session = attributes[:'is_anon_session']
      end

      if attributes.key?(:'session_id')
        self.session_id = attributes[:'session_id']
      end

      if attributes.key?(:'username')
        self.username = attributes[:'username']
      end

      if attributes.key?(:'website_url')
        self.website_url = attributes[:'website_url']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          authorized == o.authorized &&
          avatar_src == o.avatar_src &&
          badges == o.badges &&
          display_label == o.display_label &&
          display_name == o.display_name &&
          email == o.email &&
          group_ids == o.group_ids &&
          has_blocked_users == o.has_blocked_users &&
          is_anon_session == o.is_anon_session &&
          session_id == o.session_id &&
          username == o.username &&
          website_url == o.website_url
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, authorized, avatar_src, badges, display_label, display_name, email, group_ids, has_blocked_users, is_anon_session, session_id, username, website_url].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
