=begin
#fastcomments

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.18.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for FastCommentsClient::DefaultApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DefaultApi' do
  before do
    # run before each test
    @api_instance = FastCommentsClient::DefaultApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DefaultApi' do
    it 'should create an instance of DefaultApi' do
      expect(@api_instance).to be_instance_of(FastCommentsClient::DefaultApi)
    end
  end

  # unit tests for add_domain_config
  # @param tenant_id 
  # @param add_domain_config_params 
  # @param [Hash] opts the optional parameters
  # @return [AddDomainConfig200Response]
  describe 'add_domain_config test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for add_page
  # @param tenant_id 
  # @param create_api_page_data 
  # @param [Hash] opts the optional parameters
  # @return [AddPageAPIResponse]
  describe 'add_page test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for add_sso_user
  # @param tenant_id 
  # @param create_apisso_user_data 
  # @param [Hash] opts the optional parameters
  # @return [AddSSOUserAPIResponse]
  describe 'add_sso_user test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for aggregate
  # Aggregates documents by grouping them (if groupBy is provided) and applying multiple operations. Different operations (e.g. sum, countDistinct, avg, etc.) are supported.
  # @param tenant_id 
  # @param aggregation_request 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :parent_tenant_id 
  # @option opts [Boolean] :include_stats 
  # @return [AggregationResponse]
  describe 'aggregate test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for aggregate_question_results
  # @param tenant_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :question_id 
  # @option opts [Array<String>] :question_ids 
  # @option opts [String] :url_id 
  # @option opts [AggregateTimeBucket] :time_bucket 
  # @option opts [Time] :start_date 
  # @option opts [Boolean] :force_recalculate 
  # @return [AggregateQuestionResults200Response]
  describe 'aggregate_question_results test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for block_user_from_comment
  # @param tenant_id 
  # @param id 
  # @param block_from_comment_params 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :user_id 
  # @option opts [String] :anon_user_id 
  # @return [BlockFromCommentPublic200Response]
  describe 'block_user_from_comment test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for bulk_aggregate_question_results
  # @param tenant_id 
  # @param bulk_aggregate_question_results_request 
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :force_recalculate 
  # @return [BulkAggregateQuestionResults200Response]
  describe 'bulk_aggregate_question_results test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for combine_comments_with_question_results
  # @param tenant_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :question_id 
  # @option opts [Array<String>] :question_ids 
  # @option opts [String] :url_id 
  # @option opts [Time] :start_date 
  # @option opts [Boolean] :force_recalculate 
  # @option opts [Float] :min_value 
  # @option opts [Float] :max_value 
  # @option opts [Float] :limit 
  # @return [CombineCommentsWithQuestionResults200Response]
  describe 'combine_comments_with_question_results test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_feed_post
  # @param tenant_id 
  # @param create_feed_post_params 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :broadcast_id 
  # @option opts [Boolean] :is_live 
  # @option opts [Boolean] :do_spam_check 
  # @option opts [Boolean] :skip_dup_check 
  # @return [CreateFeedPost200Response]
  describe 'create_feed_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_subscription
  # @param tenant_id 
  # @param create_api_user_subscription_data 
  # @param [Hash] opts the optional parameters
  # @return [CreateSubscriptionAPIResponse]
  describe 'create_subscription test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_user_badge
  # @param tenant_id 
  # @param create_user_badge_params 
  # @param [Hash] opts the optional parameters
  # @return [CreateUserBadge200Response]
  describe 'create_user_badge test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_comment
  # @param tenant_id 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :context_user_id 
  # @option opts [Boolean] :is_live 
  # @return [DeleteComment200Response]
  describe 'delete_comment test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_domain_config
  # @param tenant_id 
  # @param domain 
  # @param [Hash] opts the optional parameters
  # @return [DeleteDomainConfig200Response]
  describe 'delete_domain_config test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_page
  # @param tenant_id 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [DeletePageAPIResponse]
  describe 'delete_page test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_sso_user
  # @param tenant_id 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :delete_comments 
  # @option opts [String] :comment_delete_mode 
  # @return [DeleteSSOUserAPIResponse]
  describe 'delete_sso_user test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_subscription
  # @param tenant_id 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :user_id 
  # @return [DeleteSubscriptionAPIResponse]
  describe 'delete_subscription test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_user_badge
  # @param tenant_id 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [UpdateUserBadge200Response]
  describe 'delete_user_badge test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for flag_comment
  # @param tenant_id 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :user_id 
  # @option opts [String] :anon_user_id 
  # @return [FlagComment200Response]
  describe 'flag_comment test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_audit_logs
  # @param tenant_id 
  # @param [Hash] opts the optional parameters
  # @option opts [Float] :limit 
  # @option opts [Float] :skip 
  # @option opts [SORTDIR] :order 
  # @option opts [Float] :after 
  # @option opts [Float] :before 
  # @return [GetAuditLogs200Response]
  describe 'get_audit_logs test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_comment
  # @param tenant_id 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [GetComment200Response]
  describe 'get_comment test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_comments
  # @param tenant_id 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page 
  # @option opts [Integer] :limit 
  # @option opts [Integer] :skip 
  # @option opts [Boolean] :as_tree 
  # @option opts [Integer] :skip_children 
  # @option opts [Integer] :limit_children 
  # @option opts [Integer] :max_tree_depth 
  # @option opts [String] :url_id 
  # @option opts [String] :user_id 
  # @option opts [String] :anon_user_id 
  # @option opts [String] :context_user_id 
  # @option opts [String] :hash_tag 
  # @option opts [String] :parent_id 
  # @option opts [SortDirections] :direction 
  # @return [GetComments200Response]
  describe 'get_comments test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_domain_config
  # @param tenant_id 
  # @param domain 
  # @param [Hash] opts the optional parameters
  # @return [GetDomainConfig200Response]
  describe 'get_domain_config test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_domain_configs
  # @param tenant_id 
  # @param [Hash] opts the optional parameters
  # @return [GetDomainConfigs200Response]
  describe 'get_domain_configs test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_feed_posts
  #  req tenantId afterId
  # @param tenant_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :after_id 
  # @option opts [Integer] :limit 
  # @option opts [Array<String>] :tags 
  # @return [GetFeedPosts200Response]
  describe 'get_feed_posts test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_page_by_urlid
  # @param tenant_id 
  # @param url_id 
  # @param [Hash] opts the optional parameters
  # @return [GetPageByURLIdAPIResponse]
  describe 'get_page_by_urlid test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_pages
  # @param tenant_id 
  # @param [Hash] opts the optional parameters
  # @return [GetPagesAPIResponse]
  describe 'get_pages test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_sso_user_by_email
  # @param tenant_id 
  # @param email 
  # @param [Hash] opts the optional parameters
  # @return [GetSSOUserByEmailAPIResponse]
  describe 'get_sso_user_by_email test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_sso_user_by_id
  # @param tenant_id 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [GetSSOUserByIdAPIResponse]
  describe 'get_sso_user_by_id test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_sso_users
  # @param tenant_id 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :skip 
  # @return [GetSSOUsers200Response]
  describe 'get_sso_users test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_subscriptions
  # @param tenant_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :user_id 
  # @return [GetSubscriptionsAPIResponse]
  describe 'get_subscriptions test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_user_badge
  # @param tenant_id 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [GetUserBadge200Response]
  describe 'get_user_badge test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_user_badge_progress_by_id
  # @param tenant_id 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [GetUserBadgeProgressById200Response]
  describe 'get_user_badge_progress_by_id test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_user_badge_progress_by_user_id
  # @param tenant_id 
  # @param user_id 
  # @param [Hash] opts the optional parameters
  # @return [GetUserBadgeProgressById200Response]
  describe 'get_user_badge_progress_by_user_id test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_user_badge_progress_list
  # @param tenant_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :user_id 
  # @option opts [Float] :limit 
  # @option opts [Float] :skip 
  # @return [GetUserBadgeProgressList200Response]
  describe 'get_user_badge_progress_list test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_user_badges
  # @param tenant_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :user_id 
  # @option opts [String] :badge_id 
  # @option opts [Float] :type 
  # @option opts [Boolean] :displayed_on_comments 
  # @option opts [Float] :limit 
  # @option opts [Float] :skip 
  # @return [GetUserBadges200Response]
  describe 'get_user_badges test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for patch_domain_config
  # @param tenant_id 
  # @param domain_to_update 
  # @param patch_domain_config_params 
  # @param [Hash] opts the optional parameters
  # @return [GetDomainConfig200Response]
  describe 'patch_domain_config test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for patch_page
  # @param tenant_id 
  # @param id 
  # @param update_api_page_data 
  # @param [Hash] opts the optional parameters
  # @return [PatchPageAPIResponse]
  describe 'patch_page test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for patch_sso_user
  # @param tenant_id 
  # @param id 
  # @param update_apisso_user_data 
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :update_comments 
  # @return [PatchSSOUserAPIResponse]
  describe 'patch_sso_user test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for put_domain_config
  # @param tenant_id 
  # @param domain_to_update 
  # @param update_domain_config_params 
  # @param [Hash] opts the optional parameters
  # @return [GetDomainConfig200Response]
  describe 'put_domain_config test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for put_sso_user
  # @param tenant_id 
  # @param id 
  # @param update_apisso_user_data 
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :update_comments 
  # @return [PutSSOUserAPIResponse]
  describe 'put_sso_user test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for save_comment
  # @param tenant_id 
  # @param create_comment_params 
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :is_live 
  # @option opts [Boolean] :do_spam_check 
  # @option opts [Boolean] :send_emails 
  # @option opts [Boolean] :populate_notifications 
  # @return [SaveComment200Response]
  describe 'save_comment test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for save_comments_bulk
  # @param tenant_id 
  # @param create_comment_params 
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :is_live 
  # @option opts [Boolean] :do_spam_check 
  # @option opts [Boolean] :send_emails 
  # @option opts [Boolean] :populate_notifications 
  # @return [Array<SaveComment200Response>]
  describe 'save_comments_bulk test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for un_block_user_from_comment
  # @param tenant_id 
  # @param id 
  # @param un_block_from_comment_params 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :user_id 
  # @option opts [String] :anon_user_id 
  # @return [UnBlockCommentPublic200Response]
  describe 'un_block_user_from_comment test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for un_flag_comment
  # @param tenant_id 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :user_id 
  # @option opts [String] :anon_user_id 
  # @return [FlagComment200Response]
  describe 'un_flag_comment test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_comment
  # @param tenant_id 
  # @param id 
  # @param updatable_comment_params 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :context_user_id 
  # @option opts [Boolean] :do_spam_check 
  # @option opts [Boolean] :is_live 
  # @return [FlagCommentPublic200Response]
  describe 'update_comment test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_feed_post
  # @param tenant_id 
  # @param id 
  # @param feed_post 
  # @param [Hash] opts the optional parameters
  # @return [FlagCommentPublic200Response]
  describe 'update_feed_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_user_badge
  # @param tenant_id 
  # @param id 
  # @param update_user_badge_params 
  # @param [Hash] opts the optional parameters
  # @return [UpdateUserBadge200Response]
  describe 'update_user_badge test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
