=begin
#fastcomments

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for FastCommentsClient::PublicApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PublicApi' do
  before do
    # run before each test
    @api_instance = FastCommentsClient::PublicApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PublicApi' do
    it 'should create an instance of PublicApi' do
      expect(@api_instance).to be_instance_of(FastCommentsClient::PublicApi)
    end
  end

  # unit tests for block_from_comment_public
  # @param tenant_id 
  # @param comment_id 
  # @param public_block_from_comment_params 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :sso 
  # @return [BlockSuccess]
  describe 'block_from_comment_public test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for checked_comments_for_blocked
  # @param tenant_id 
  # @param comment_ids A comma separated list of comment ids.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :sso 
  # @return [CheckBlockedCommentsResponse]
  describe 'checked_comments_for_blocked test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_comment_public
  # @param tenant_id 
  # @param url_id 
  # @param broadcast_id 
  # @param comment_data 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :session_id 
  # @option opts [String] :sso 
  # @return [SaveCommentsResponseWithPresence]
  describe 'create_comment_public test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_feed_post_public
  # @param tenant_id 
  # @param create_feed_post_params 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :broadcast_id 
  # @option opts [String] :sso 
  # @return [CreateFeedPostResponse]
  describe 'create_feed_post_public test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_v1_page_react
  # @param tenant_id 
  # @param url_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :title 
  # @return [CreateV1PageReact]
  describe 'create_v1_page_react test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_v2_page_react
  # @param tenant_id 
  # @param url_id 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :title 
  # @return [CreateV1PageReact]
  describe 'create_v2_page_react test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_comment_public
  # @param tenant_id 
  # @param comment_id 
  # @param broadcast_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :edit_key 
  # @option opts [String] :sso 
  # @return [PublicAPIDeleteCommentResponse]
  describe 'delete_comment_public test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_comment_vote
  # @param tenant_id 
  # @param comment_id 
  # @param vote_id 
  # @param url_id 
  # @param broadcast_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :edit_key 
  # @option opts [String] :sso 
  # @return [VoteDeleteResponse]
  describe 'delete_comment_vote test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_feed_post_public
  # @param tenant_id 
  # @param post_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :broadcast_id 
  # @option opts [String] :sso 
  # @return [DeleteFeedPostPublicResponse]
  describe 'delete_feed_post_public test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_v1_page_react
  # @param tenant_id 
  # @param url_id 
  # @param [Hash] opts the optional parameters
  # @return [CreateV1PageReact]
  describe 'delete_v1_page_react test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_v2_page_react
  # @param tenant_id 
  # @param url_id 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [CreateV1PageReact]
  describe 'delete_v2_page_react test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for flag_comment_public
  # @param tenant_id 
  # @param comment_id 
  # @param is_flagged 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :sso 
  # @return [APIEmptyResponse]
  describe 'flag_comment_public test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_comment_text
  # @param tenant_id 
  # @param comment_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :edit_key 
  # @option opts [String] :sso 
  # @return [PublicAPIGetCommentTextResponse]
  describe 'get_comment_text test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_comment_vote_user_names
  # @param tenant_id 
  # @param comment_id 
  # @param dir 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :sso 
  # @return [GetCommentVoteUserNamesSuccessResponse]
  describe 'get_comment_vote_user_names test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_comments_for_user
  # @param [Hash] opts the optional parameters
  # @option opts [String] :user_id 
  # @option opts [SortDirections] :direction 
  # @option opts [String] :replies_to_user_id 
  # @option opts [Float] :page 
  # @option opts [Boolean] :includei10n 
  # @option opts [String] :locale 
  # @option opts [Boolean] :is_crawler 
  # @return [GetCommentsForUserResponse]
  describe 'get_comments_for_user test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_comments_public
  #  req tenantId urlId
  # @param tenant_id 
  # @param url_id 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page 
  # @option opts [SortDirections] :direction 
  # @option opts [String] :sso 
  # @option opts [Integer] :skip 
  # @option opts [Integer] :skip_children 
  # @option opts [Integer] :limit 
  # @option opts [Integer] :limit_children 
  # @option opts [Boolean] :count_children 
  # @option opts [String] :fetch_page_for_comment_id 
  # @option opts [Boolean] :include_config 
  # @option opts [Boolean] :count_all 
  # @option opts [Boolean] :includei10n 
  # @option opts [String] :locale 
  # @option opts [String] :modules 
  # @option opts [Boolean] :is_crawler 
  # @option opts [Boolean] :include_notification_count 
  # @option opts [Boolean] :as_tree 
  # @option opts [Integer] :max_tree_depth 
  # @option opts [Boolean] :use_full_translation_ids 
  # @option opts [String] :parent_id 
  # @option opts [String] :search_text 
  # @option opts [Array<String>] :hash_tags 
  # @option opts [String] :user_id 
  # @option opts [String] :custom_config_str 
  # @option opts [String] :after_comment_id 
  # @option opts [String] :before_comment_id 
  # @return [GetCommentsResponseWithPresencePublicComment]
  describe 'get_comments_public test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_event_log
  #  req tenantId urlId userIdWS
  # @param tenant_id 
  # @param url_id 
  # @param user_id_ws 
  # @param start_time 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :end_time 
  # @return [GetEventLogResponse]
  describe 'get_event_log test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_feed_posts_public
  #  req tenantId afterId
  # @param tenant_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :after_id 
  # @option opts [Integer] :limit 
  # @option opts [Array<String>] :tags 
  # @option opts [String] :sso 
  # @option opts [Boolean] :is_crawler 
  # @option opts [Boolean] :include_user_info 
  # @return [PublicFeedPostsResponse]
  describe 'get_feed_posts_public test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_feed_posts_stats
  # @param tenant_id 
  # @param post_ids 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :sso 
  # @return [FeedPostsStatsResponse]
  describe 'get_feed_posts_stats test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_gif_large
  # @param tenant_id 
  # @param large_internal_url_sanitized 
  # @param [Hash] opts the optional parameters
  # @return [GifGetLargeResponse]
  describe 'get_gif_large test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_gifs_search
  # @param tenant_id 
  # @param search 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :locale 
  # @option opts [String] :rating 
  # @option opts [Float] :page 
  # @return [GetGifsSearchResponse]
  describe 'get_gifs_search test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_gifs_trending
  # @param tenant_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :locale 
  # @option opts [String] :rating 
  # @option opts [Float] :page 
  # @return [GetGifsTrendingResponse]
  describe 'get_gifs_trending test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_global_event_log
  #  req tenantId urlId userIdWS
  # @param tenant_id 
  # @param url_id 
  # @param user_id_ws 
  # @param start_time 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :end_time 
  # @return [GetEventLogResponse]
  describe 'get_global_event_log test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_offline_users
  # Past commenters on the page who are NOT currently online. Sorted by displayName. Use this after exhausting /users/online to render a \&quot;Members\&quot; section. Cursor pagination on commenterName: server walks the partial {tenantId, urlId, commenterName} index from afterName forward via $gt, no $skip cost.
  # @param tenant_id 
  # @param url_id Page URL identifier (cleaned server-side).
  # @param [Hash] opts the optional parameters
  # @option opts [String] :after_name Cursor: pass nextAfterName from the previous response.
  # @option opts [String] :after_user_id Cursor tiebreaker: pass nextAfterUserId from the previous response. Required when afterName is set so name-ties don&#39;t drop entries.
  # @return [PageUsersOfflineResponse]
  describe 'get_offline_users test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_online_users
  # Currently-online viewers of a page: people whose websocket session is subscribed to the page right now. Returns anonCount + totalCount (room-wide subscribers, including anon viewers we don&#39;t enumerate).
  # @param tenant_id 
  # @param url_id Page URL identifier (cleaned server-side).
  # @param [Hash] opts the optional parameters
  # @option opts [String] :after_name Cursor: pass nextAfterName from the previous response.
  # @option opts [String] :after_user_id Cursor tiebreaker: pass nextAfterUserId from the previous response. Required when afterName is set so name-ties don&#39;t drop entries.
  # @return [PageUsersOnlineResponse]
  describe 'get_online_users test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_pages_public
  # List pages for a tenant. Used by the FChat desktop client to populate its room list. Requires &#x60;enableFChat&#x60; to be true on the resolved custom config for each page. Pages that require SSO are filtered against the requesting user&#39;s group access.
  # @param tenant_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :cursor Opaque pagination cursor returned as &#x60;nextCursor&#x60; from a prior request. Tied to the same &#x60;sortBy&#x60;.
  # @option opts [Integer] :limit 1..200, default 50
  # @option opts [String] :q Optional case-insensitive title prefix filter.
  # @option opts [PagesSortBy] :sort_by Sort order. &#x60;updatedAt&#x60; (default, newest first), &#x60;commentCount&#x60; (most comments first), or &#x60;title&#x60; (alphabetical).
  # @option opts [Boolean] :has_comments If true, only return pages with at least one comment.
  # @return [GetPublicPagesResponse]
  describe 'get_pages_public test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_translations
  # @param namespace 
  # @param component 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :locale 
  # @option opts [Boolean] :use_full_translation_ids 
  # @return [GetTranslationsResponse]
  describe 'get_translations test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_user_notification_count
  # @param tenant_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :sso 
  # @return [GetUserNotificationCountResponse]
  describe 'get_user_notification_count test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_user_notifications
  # @param tenant_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :url_id Used to determine whether the current page is subscribed.
  # @option opts [Integer] :page_size 
  # @option opts [String] :after_id 
  # @option opts [Boolean] :include_context 
  # @option opts [Integer] :after_created_at 
  # @option opts [Boolean] :unread_only 
  # @option opts [Boolean] :dm_only 
  # @option opts [Boolean] :no_dm 
  # @option opts [Boolean] :include_translations 
  # @option opts [Boolean] :include_tenant_notifications 
  # @option opts [String] :sso 
  # @return [GetMyNotificationsResponse]
  describe 'get_user_notifications test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_user_presence_statuses
  # @param tenant_id 
  # @param url_id_ws 
  # @param user_ids 
  # @param [Hash] opts the optional parameters
  # @return [GetUserPresenceStatusesResponse]
  describe 'get_user_presence_statuses test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_user_reacts_public
  # @param tenant_id 
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :post_ids 
  # @option opts [String] :sso 
  # @return [UserReactsResponse]
  describe 'get_user_reacts_public test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_users_info
  # Bulk user info for a tenant. Given userIds, return display info from User / SSOUser. Used by the comment widget to enrich users that just appeared via a presence event. No page context: privacy is enforced uniformly (private profiles are masked).
  # @param tenant_id 
  # @param ids Comma-delimited userIds.
  # @param [Hash] opts the optional parameters
  # @return [PageUsersInfoResponse]
  describe 'get_users_info test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_v1_page_likes
  # @param tenant_id 
  # @param url_id 
  # @param [Hash] opts the optional parameters
  # @return [GetV1PageLikes]
  describe 'get_v1_page_likes test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_v2_page_react_users
  # @param tenant_id 
  # @param url_id 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [GetV2PageReactUsersResponse]
  describe 'get_v2_page_react_users test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_v2_page_reacts
  # @param tenant_id 
  # @param url_id 
  # @param [Hash] opts the optional parameters
  # @return [GetV2PageReacts]
  describe 'get_v2_page_reacts test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for lock_comment
  # @param tenant_id 
  # @param comment_id 
  # @param broadcast_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :sso 
  # @return [APIEmptyResponse]
  describe 'lock_comment test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for logout_public
  # @param [Hash] opts the optional parameters
  # @return [APIEmptyResponse]
  describe 'logout_public test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for pin_comment
  # @param tenant_id 
  # @param comment_id 
  # @param broadcast_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :sso 
  # @return [ChangeCommentPinStatusResponse]
  describe 'pin_comment test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for react_feed_post_public
  # @param tenant_id 
  # @param post_id 
  # @param react_body_params 
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :is_undo 
  # @option opts [String] :broadcast_id 
  # @option opts [String] :sso 
  # @return [ReactFeedPostResponse]
  describe 'react_feed_post_public test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for reset_user_notification_count
  # @param tenant_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :sso 
  # @return [ResetUserNotificationsResponse]
  describe 'reset_user_notification_count test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for reset_user_notifications
  # @param tenant_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :after_id 
  # @option opts [Integer] :after_created_at 
  # @option opts [Boolean] :unread_only 
  # @option opts [Boolean] :dm_only 
  # @option opts [Boolean] :no_dm 
  # @option opts [String] :sso 
  # @return [ResetUserNotificationsResponse]
  describe 'reset_user_notifications test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for search_users
  # @param tenant_id 
  # @param url_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :username_starts_with 
  # @option opts [Array<String>] :mention_group_ids 
  # @option opts [String] :sso 
  # @option opts [String] :search_section 
  # @return [SearchUsersResult]
  describe 'search_users test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for set_comment_text
  # @param tenant_id 
  # @param comment_id 
  # @param broadcast_id 
  # @param comment_text_update_request 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :edit_key 
  # @option opts [String] :sso 
  # @return [PublicAPISetCommentTextResponse]
  describe 'set_comment_text test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for un_block_comment_public
  # @param tenant_id 
  # @param comment_id 
  # @param public_block_from_comment_params 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :sso 
  # @return [UnblockSuccess]
  describe 'un_block_comment_public test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for un_lock_comment
  # @param tenant_id 
  # @param comment_id 
  # @param broadcast_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :sso 
  # @return [APIEmptyResponse]
  describe 'un_lock_comment test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for un_pin_comment
  # @param tenant_id 
  # @param comment_id 
  # @param broadcast_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :sso 
  # @return [ChangeCommentPinStatusResponse]
  describe 'un_pin_comment test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_feed_post_public
  # @param tenant_id 
  # @param post_id 
  # @param update_feed_post_params 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :broadcast_id 
  # @option opts [String] :sso 
  # @return [CreateFeedPostResponse]
  describe 'update_feed_post_public test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_user_notification_comment_subscription_status
  # Enable or disable notifications for a specific comment.
  # @param tenant_id 
  # @param notification_id 
  # @param opted_in_or_out 
  # @param comment_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :sso 
  # @return [UpdateUserNotificationCommentSubscriptionStatusResponse]
  describe 'update_user_notification_comment_subscription_status test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_user_notification_page_subscription_status
  # Enable or disable notifications for a page. When users are subscribed to a page, notifications are created for new root comments, and also
  # @param tenant_id 
  # @param url_id 
  # @param url 
  # @param page_title 
  # @param subscribed_or_unsubscribed 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :sso 
  # @return [UpdateUserNotificationPageSubscriptionStatusResponse]
  describe 'update_user_notification_page_subscription_status test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_user_notification_status
  # @param tenant_id 
  # @param notification_id 
  # @param new_status 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :sso 
  # @return [UpdateUserNotificationStatusResponse]
  describe 'update_user_notification_status test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for upload_image
  # Upload and resize an image
  # @param tenant_id 
  # @param file 
  # @param [Hash] opts the optional parameters
  # @option opts [SizePreset] :size_preset Size preset: \&quot;Default\&quot; (1000x1000px) or \&quot;CrossPlatform\&quot; (creates sizes for popular devices)
  # @option opts [String] :url_id Page id that upload is happening from, to configure
  # @return [UploadImageResponse]
  describe 'upload_image test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for vote_comment
  # @param tenant_id 
  # @param comment_id 
  # @param url_id 
  # @param broadcast_id 
  # @param vote_body_params 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :session_id 
  # @option opts [String] :sso 
  # @return [VoteResponse]
  describe 'vote_comment test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
